In [3]:
import requests
import pandas as pd

# -----------------------------
# CONFIG – fill these in
# -----------------------------
API_KEY = "3b339a99725dc0efa820ed87b0db4541"
TOKEN   = "ATTAdc78f81723bc85deb590dd40f9608ec7ec7dda4df5f9396a606240b8e4d4ea20436E01D9"

BOARD_ID = "6879845badb2291c02fc3854"

# Put the list IDs you care about here
LIST_IDS = [
    "698d4586723fd10aac6f01d0"  # Purchase T-1
]
    
OUTPUT_CSV = r"C:\\Users\\User\\OneDrive\\Momentum\\Scripts\\Signal_Archive\\todays_purchase.csv"

# -----------------------------
# Helper: Trello GET wrapper
# -----------------------------
BASE_URL = "https://api.trello.com/1"

def trello_get(path, params=None):
    if params is None:
        params = {}
    auth_params = {"key": API_KEY, "token": TOKEN}
    auth_params.update(params)
    url = f"{BASE_URL}{path}"
    resp = requests.get(url, params=auth_params, timeout=60)
    resp.raise_for_status()
    return resp.json()

# -----------------------------
# Helper: parse description lines (variable_name : value)
# -----------------------------
def parse_description(desc_text):
    result = {}
    if not desc_text:
        return result

    for line in desc_text.splitlines():
        line = line.strip()
        if not line or ":" not in line:
            continue
        var, val = line.split(":", 1)
        result[var.strip()] = val.strip()
    return result

# -----------------------------
# Helper: get custom field value (supports text/number/checkbox/date/list)
# -----------------------------
def get_custom_field_value(cf_item, cf_def):
    """
    cf_item: one item from card["customFieldItems"]
    cf_def:  matching definition from /boards/{BOARD_ID}/customFields
    """
    value = cf_item.get("value") or {}
    cf_type = cf_def.get("type")

    if cf_type == "text":
        return value.get("text", "")

    if cf_type == "number":
        # Trello returns numbers as strings; keep as numeric where possible
        v = value.get("number", "")
        try:
            return float(v) if v != "" else ""
        except ValueError:
            return v

    if cf_type == "checkbox":
        # "true"/"false" strings
        v = value.get("checked", "")
        if v == "true":
            return True
        if v == "false":
            return False
        return ""

    if cf_type == "date":
        return value.get("date", "")

    if cf_type == "list":
        # Dropdown: item stores idValue, definition stores options with text
        id_value = cf_item.get("idValue")
        if not id_value:
            return ""
        options = cf_def.get("options", []) or []
        for opt in options:
            if opt.get("id") == id_value:
                return (opt.get("value") or {}).get("text", "")
        # fallback if not found
        return id_value

    # Unknown type fallback
    return value or ""

# -----------------------------
# 1. Get custom field definitions for the board
# -----------------------------
custom_fields_raw = trello_get(f"/boards/{BOARD_ID}/customFields")

custom_field_defs = {}
custom_field_names = []

for cf in custom_fields_raw:
    cf_id = cf["id"]
    custom_field_defs[cf_id] = cf
    custom_field_names.append(cf["name"])

# -----------------------------
# 2. Get list names for the entire board
# -----------------------------
board_lists = trello_get(f"/boards/{BOARD_ID}/lists", params={"fields": "name"})
list_name_lookup = {lst["id"]: lst["name"] for lst in board_lists}
# -----------------------------
# 3. Collect card data from lists
# -----------------------------
all_rows = []

for list_id in LIST_IDS:
    cards = trello_get(
        f"/lists/{list_id}/cards",
        params={"fields": "name,desc,idList", "customFieldItems": "true"},
    )

    for card in cards:
        row = {}
        row["Title"] = card.get("name", "")
        row["Card_ID"] = card.get("id", "")
        row["List_Name"] = list_name_lookup.get(card.get("idList"), "")

        # Parse description vars
        desc_vars = parse_description(card.get("desc", ""))
        row.update(desc_vars)

        # Add custom field values
        for cf_item in card.get("customFieldItems", []):
            cf_id = cf_item.get("idCustomField")
            cf_def = custom_field_defs.get(cf_id)
            if not cf_def:
                continue
            row[cf_def["name"]] = get_custom_field_value(cf_item, cf_def)

        all_rows.append(row)

# -----------------------------
# 4. Build DataFrame
# -----------------------------
df = pd.DataFrame(all_rows)

# Safe column ordering (won't crash if empty)
base_cols = [c for c in ["Title", "List_Name"] if c in df.columns]
other_cols = [c for c in df.columns if c not in base_cols]

cf_cols_in_df = [name for name in custom_field_names if name in other_cols]
desc_cols = sorted([c for c in other_cols if c not in cf_cols_in_df])

final_cols = base_cols + cf_cols_in_df + desc_cols
df = df.reindex(columns=final_cols)
df['n_components'] = df['PARAM n-value']
df['poly_degree'] = df['PARAM regression']
df['std_multiplier'] = df['PARAM sensitivity']
df['train_window'] = df['PARAM training period']


# -----------------------------
# 5. Save CSV
# -----------------------------
df.to_csv(OUTPUT_CSV, index=False)
print(f"Exported {len(df)} cards to {OUTPUT_CSV}")

Exported 32 cards to C:\\Users\\User\\OneDrive\\Momentum\\Scripts\\Signal_Archive\\todays_purchase.csv

In [4]:
# --- Cell 1: Imports ---
import pandas as pd
import numpy as np
from pandas.tseries.offsets import BDay

In [5]:
import datetime
import requests # Ensure requests is imported
import time

# Ensure TRELLO_API_BASE_URL is correctly set from the kernel state
TRELLO_API_BASE_URL = "https://api.trello.com/1/"

# Assuming TRELLO_KEY and TRELLO_TOKEN are already available from the kernel state
TRELLO_KEY = '3b339a99725dc0efa820ed87b0db4541' # If keys were in secrets, this is how you'd get them.
TRELLO_TOKEN = 'ATTAdc78f81723bc85deb590dd40f9608ec7ec7dda4df5f9396a606240b8e4d4ea20436E01D9'

RATE_LIMIT_SLEEP_SECS = 0.2

def trello_api_request(endpoint, method='GET', params=None, data=None, files=None):
    if params is None:
        params = {}
    if data is None:
        data = {}

    params['key'] = TRELLO_KEY
    params['token'] = TRELLO_TOKEN

    url = f"{TRELLO_API_BASE_URL}{endpoint}"
    try:
        if method == 'GET':
            response = requests.get(url, params=params)
        elif method == 'POST':
            # For POST requests, parameters like name, desc, idList go into 'data'
            # and key/token typically go into 'params' or sometimes also 'data'.
            # Trello API typically uses params for key/token and data for card attributes.
            post_params = {'key': TRELLO_KEY, 'token': TRELLO_TOKEN}
            post_params.update(params)
            response = requests.post(url, params=post_params, data=data, files=files)
        elif method == 'PUT':  # Add PUT method
            put_params = {'key': TRELLO_KEY, 'token': TRELLO_TOKEN}
            response = requests.put(url, params=put_params, data=data)
        else:
            raise ValueError(f"Unsupported HTTP method: {method}")

        response.raise_for_status() # Raise HTTPError for bad responses (4xx or 5xx)
        time.sleep(RATE_LIMIT_SLEEP_SECS)
        return response.json()
    except requests.exceptions.RequestException as e:
        print(f"API request failed for endpoint {endpoint} (method: {method}): {e}")
        return None

print("Redefined 'trello_api_request' function to support GET, POST, PUT, and file uploads.")

Redefined 'trello_api_request' function to support GET, POST, PUT, and file uploads.

In [6]:
def attach_plot_to_card(card_id, plot_filepath, filename=None, set_cover=False):
    if not filename:
        filename = Path(plot_filepath).name

    attachments_endpoint = f"cards/{card_id}/attachments"

    try:
        with open(plot_filepath, 'rb') as f:
            files = {'file': (filename, f, 'image/png')}
            attachment_response = trello_api_request(
                attachments_endpoint,
                method='POST',
                data={'name': filename},
                params={'setCover': str(set_cover).lower()},
                files=files
            )

        if attachment_response:
            print(f"Successfully attached {filename} to card {card_id}")
            return attachment_response
        else:
            print(f"Failed to attach {filename} to card {card_id}")
            return None
    except FileNotFoundError:
        print(f"Error: Plot file not found at {plot_filepath}")
        return None
    except Exception as e:
        print(f"An error occurred while attaching plot {filename} to card {card_id}: {e}")
        return None

print("Defined 'attach_plot_to_card' helper function.")

Defined 'attach_plot_to_card' helper function.

In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import os
from io import BytesIO
import yfinance as yf
import numpy as np
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from IPython.display import display, HTML
from itertools import product
from tqdm import tqdm
from datetime import datetime, timedelta # Import datetime and timedelta
import pytz # Import pytz for timezone handling


# === Configuration ===
TICKER_FILE = r'C:\\Users\\User\\OneDrive\\Momentum\\Scripts\\Signal_Archive\\todays_purchase.csv'
years = 7
initial_capital = 10000
EXCEL_OUTPUT = 'Daily_Reports/Todays_Alerts.xlsx'
PLOTS_DIR = 'Daily_Reports'
buffer_days = 63
risk_factor = 1.0
trade_multiplier = 1.0


os.makedirs(PLOTS_DIR, exist_ok=True)

def get_clean_financial_data(ticker, start_date, end_date):
    data = yf.download(ticker, start=start_date, end=end_date)
    data.columns = data.columns.get_level_values(0)
    data = data.ffill()
    data.index = data.index.tz_localize(None)
    return data

def prepare_data(data):
    data = data.reset_index()
    data['Date_Ordinal'] = pd.to_numeric(data['Date'].map(pd.Timestamp.toordinal))
    scaler = StandardScaler()
    data['Close_Scaled'] = scaler.fit_transform(data[['Close']])
    X = data[['Date_Ordinal']].values
    y = data['Close_Scaled'].values
    return X, y, data, scaler

def train_models_rolling(X, y, n_components, degree, train_window):
    y_pred = np.full_like(y, np.nan)
    for i in range(train_window, len(X)):
        X_train = X[i-train_window:i]
        y_train = y[i-train_window:i]
        gmm = GaussianMixture(n_components=n_components, covariance_type='diag', random_state=42)
        gmm.fit(X_train)
        latent_features = gmm.predict_proba(X_train)
        X_latent = np.hstack([X_train, latent_features])
        poly_reg = make_pipeline(PolynomialFeatures(degree=degree), LinearRegression())
        poly_reg.fit(X_latent, y_train)
        current_latent = gmm.predict_proba(X[i].reshape(1, -1))
        current_X_latent = np.hstack([X[i].reshape(1, -1), current_latent])
        y_pred[i] = poly_reg.predict(current_X_latent)[0]
    return y_pred

def generate_signals_rolling(data, y_pred, train_window, std_multiplier):
    window = train_window
    residuals = data['Close'] - y_pred
    data['Upper_Bound'] = np.nan
    data['Lower_Bound'] = np.nan
    for i in range(window, len(data)):
        current_std = np.std(residuals.iloc[i-window:i])
        data.loc[data.index[i], 'Upper_Bound'] = y_pred[i] + std_multiplier * current_std
        data.loc[data.index[i], 'Lower_Bound'] = y_pred[i] - std_multiplier * current_std
    data['Buy_Signal'] = np.where(data['Close'] < data['Lower_Bound'], 1, 0)
    data['Sell_Signal'] = np.where(data['Close'] > data['Upper_Bound'], 1, 0)
    return data

def plot_trading_signals(data, ticker):
    """Plot the trading signals with price and bounds"""
    plt.figure(figsize=(14, 8))

    # Plot closing price
    plt.plot(data['Date'], data['Close'], label='Close Price', color='black', alpha=0.8, linewidth=1.5)

    # Plot predicted values
    plt.plot(data['Date'], data['Predicted'], label='Predicted Price', color='blue', alpha=0.7, linestyle='--')

    # Plot bounds
    plt.plot(data['Date'], data['Upper_Bound'], label='Upper Bound', color='red', alpha=0.5, linestyle=':')
    plt.plot(data['Date'], data['Lower_Bound'], label='Lower Bound', color='green', alpha=0.5, linestyle=':')

    # Plot signals
    buy_signals = data[data['Buy_Signal'] == 1]
    sell_signals = data[data['Sell_Signal'] == 1]

    plt.scatter(buy_signals['Date'], buy_signals['Close'],
                label='Buy Signal', color='green', marker='^', s=100, alpha=1)
    plt.scatter(sell_signals['Date'], sell_signals['Close'],
                label='Sell Signal', color='red', marker='v', s=100, alpha=1)

    # Fill between bounds
    plt.fill_between(data['Date'], data['Lower_Bound'], data['Upper_Bound'],
                     color='gray', alpha=0.1, label='Trading Range')

    plt.title(f'{ticker} Trading Signals (Lookahead-Free)')
    plt.xlabel('Date')
    plt.ylabel('Price ($)')
    plt.legend(loc='upper left')
    plt.grid(True)

def plot_recent_trading_signals_with_labels(data, ticker):
    """Plot recent trading signals and label the most recent Predicted, Upper, Lower values"""
    plt.figure(figsize=(14, 8))
    plt.plot(data['Date'], data['Close'], label='Close Price', color='black', alpha=0.8, linewidth=1.5)
    plt.plot(data['Date'], data['Predicted'], label='Predicted Price', color='blue', alpha=0.7, linestyle='--')
    plt.plot(data['Date'], data['Upper_Bound'], label='Upper Bound', color='red', alpha=0.5, linestyle=':')
    plt.plot(data['Date'], data['Lower_Bound'], label='Lower Bound', color='green', alpha=0.5, linestyle=':')

    buy_signals = data[data['Buy_Signal'] == 1]
    sell_signals = data[data['Sell_Signal'] == 1]
    plt.scatter(buy_signals['Date'], buy_signals['Close'], label='Buy Signal', color='green', marker='^', s=100, alpha=1)
    plt.scatter(sell_signals['Date'], sell_signals['Close'], label='Sell Signal', color='red', marker='v', s=100, alpha=1)

    plt.fill_between(data['Date'], data['Lower_Bound'], data['Upper_Bound'], color='gray', alpha=0.1, label='Trading Range')

    # Label latest point
    latest = data.iloc[-1]
    latest_date = latest['Date']
    plt.text(latest_date, latest['Close'], f"Current Price: {latest['Close']:.2f}", color='black', fontsize=10, ha='right', va='bottom')
    plt.text(latest_date, latest['Predicted'], f"Pred: {latest['Predicted']:.2f}", color='blue', fontsize=10, ha='right', va='bottom')
    plt.text(latest_date, latest['Upper_Bound'], f"Upper: {latest['Upper_Bound']:.2f}", color='red', fontsize=10, ha='right', va='bottom')
    plt.text(latest_date, latest['Lower_Bound'], f"Lower: {latest['Lower_Bound']:.2f}", color='green', fontsize=10, ha='right', va='top')

    plt.title(f'{ticker} Trading Signals - Last 6 Months (Annotated)')
    plt.xlabel('Date')
    plt.ylabel('Price ($)')
    plt.legend(loc='upper left')
    plt.grid(True)


def backtest_strategy(data, initial_capital, train_window, buffer_days=buffer_days):
    cash = initial_capital
    shares = 0
    portfolio_value = []
    transactions = []
    position = 'out'
    buy_timer = 0
    sell_timer = 0
    pending_buy_index = None
    pending_sell_index = None
    min_price_since_buy = None
    min_price_date = None
    start_idx = train_window + buffer_days

    for i, row in data.iterrows():
        if i < start_idx:
            portfolio_value.append(cash)
            continue
        current_date = row['Date']
        current_price = row['Close']
        buy_signal = row['Buy_Signal']
        sell_signal = row['Sell_Signal']

        # BUY logic
        if position == 'out':
            if buy_signal:
                buy_timer = 3
                pending_buy_index = i
            elif buy_timer > 0:
                buy_timer -= 1
                if buy_signal:
                    buy_timer = 3
                    pending_buy_index = i

                if buy_timer == 0 and pending_buy_index is not None:
                    execution_index = i
                    if execution_index < len(data):
                        execution_date = data.loc[execution_index, 'Date']
                        execution_price = data.loc[execution_index, 'Close']
                        shares_to_buy = cash // execution_price
                        trade_value = shares_to_buy * execution_price
                        commission = 30 if trade_value < 10000 else trade_value * 0.003
                        cost = trade_value + commission

                        if shares_to_buy > 0:
                            cash -= cost
                            shares += shares_to_buy
                            position = 'long'
                            min_price_since_buy = execution_price
                            min_price_date = execution_date
                            transactions.append({
                                'Date': execution_date,
                                'Type': 'BUY',
                                'Price': execution_price,
                                'Shares': shares_to_buy,
                                'Value': trade_value,
                                'Commission': commission,
                                'Cash': cash,
                                'Position': position,
                                'Days_Held': 0,
                                'Profit_Loss': 0,
                                'Pct_Return': 0,
                                'Annualized_Return_%': 0,
                                'StopLoss%': np.nan,
                                'StopLoss_Date': pd.NaT
                            })

                    pending_buy_index = None

        # SELL logic
        elif position == 'long':
            if current_price < min_price_since_buy:
                min_price_since_buy = current_price
                min_price_date = current_date
            if sell_signal:
                sell_timer = 3
                pending_sell_index = i
            elif sell_timer > 0:
                sell_timer -= 1
                if sell_signal:
                    buy_timer = 3
                    pending_sell_index = i

                if sell_timer == 0 and pending_sell_index is not None:
                    execution_index = i
                    if execution_index < len(data):
                        execution_date = data.loc[execution_index, 'Date']
                        execution_price = data.loc[execution_index, 'Close']
                        trade_value = shares * execution_price
                        commission = 30 if trade_value < 10000 else trade_value * 0.003
                        proceeds = trade_value - commission
                        cash += proceeds

                        buy_price = transactions[-1]['Price']
                        buy_value = transactions[-1]['Value']
                        buy_date = transactions[-1]['Date']
                        days_held = (execution_date - buy_date).days

                        profit_loss = trade_value - buy_value - 2 * commission
                        pct_return = (trade_value - buy_value) / buy_value * 100
                        annualized_return = ((1 + pct_return / 100) ** (365 / days_held) - 1) * 100 if days_held > 0 else np.nan
                        stop_loss_pct = ((min_price_since_buy - buy_price) / buy_price * 100
                                         if min_price_since_buy is not None and min_price_since_buy < buy_price
                                         else 0)

                        transactions.append({
                            'Date': execution_date,
                            'Type': 'SELL',
                            'Price': execution_price,
                            'Shares': shares,
                            'Value': trade_value,
                            'Commission': commission,
                            'Cash': cash,
                            'Position': 'out',
                            'Days_Held': days_held,
                            'Profit_Loss': profit_loss,
                            'Pct_Return': pct_return,
                            'Annualized_Return_%': annualized_return,
                            'StopLoss%': stop_loss_pct,
                            'StopLoss_Date': min_price_date
                        })

                        shares = 0
                        position = 'out'
                        buy_timer = 0
                        sell_timer = 0
                        pending_buy_index = None
                        pending_sell_index = None
                        min_price_since_buy = None
                        min_price_date = None

        current_value = cash + shares * current_price
        portfolio_value.append(current_value)

    portfolio_df = pd.DataFrame({'Date': data['Date'], 'Portfolio_Value': portfolio_value, 'Stock_Price': data['Close']})
    portfolio_df = portfolio_df.iloc[start_idx:].reset_index(drop=True)
    transactions_df = pd.DataFrame(transactions)
    num_trades = len(transactions_df)

    # Handle open position with virtual SELL
    if num_trades % 2 == 1 and transactions_df.iloc[-1]['Type'] == 'BUY':
        last_buy = transactions_df.iloc[-1]
        buy_price = last_buy['Price']
        buy_date = last_buy['Date']
        shares = last_buy['Shares']
        commission = last_buy['Commission']

        current_price = portfolio_df['Stock_Price'].iloc[-1]
        current_date = portfolio_df['Date'].iloc[-1]

        days_held = (current_date - buy_date).days
        profit_loss = (current_price * shares) - (buy_price * shares) - commission
        pct_return = (current_price - buy_price) / buy_price * 100
        annualized_return = ((1 + pct_return / 100) ** (365 / days_held) - 1) * 100 if days_held > 0 else np.nan

        stop_loss_pct = ((min_price_since_buy - buy_price) / buy_price * 100
                         if min_price_since_buy is not None and min_price_since_buy < buy_price
                         else 0)

        virtual_sell = {
            'Date': current_date,
            'Type': 'SELL (Open)',
            'Price': current_price,
            'Shares': shares,
            'Value': current_price * shares,
            'Commission': 0,
            'Cash': transactions_df.iloc[-1]['Cash'],
            'Position': 'Unrealised Gain',
            'Days_Held': days_held,
            'Profit_Loss': profit_loss,
            'Pct_Return': pct_return,
            'Annualized_Return_%': annualized_return,
            'StopLoss%': stop_loss_pct,
            'StopLoss_Date': min_price_date
        }
        transactions_df = pd.concat([transactions_df, pd.DataFrame([virtual_sell])], ignore_index=True)

    return portfolio_df, transactions_df

def calculate_performance_metrics(portfolio_df, transactions_df, initial_capital, train_window, years, buffer_days=buffer_days, r_value=1500):
    """Calculate and display key performance metrics"""
    final_value = portfolio_df['Portfolio_Value'].iloc[-1]
    total_return = (final_value - initial_capital) / initial_capital * 100
    portfolio_df['Peak'] = portfolio_df['Portfolio_Value'].cummax()
    portfolio_df['Drawdown'] = (portfolio_df['Portfolio_Value'] - portfolio_df['Peak']) / portfolio_df['Peak']
    max_drawdown = portfolio_df['Drawdown'].min() * 100
    total_days_held = transactions_df['Days_Held'].dropna().sum()
    total_days = (portfolio_df['Date'].iloc[-1] - portfolio_df['Date'].iloc[0]).days
    pct_days_held = (total_days_held / total_days * 100) if total_days > 0 else 0
    start_price = portfolio_df['Stock_Price'].iloc[0]
    end_price = portfolio_df['Stock_Price'].iloc[-1]
    buy_and_hold_return = (end_price - start_price) / start_price * 100
    buy_and_hold_annualised = buy_and_hold_return / (7 - ((train_window + buffer_days)/252))
    buy_and_hold_size = initial_capital / start_price
    buy_and_hold_value = buy_and_hold_size * portfolio_df['Stock_Price'].iloc[-1]
    available_trading_days = (years - ((train_window + buffer_days)/252)) * 365
    num_trades = len(transactions_df)
    num_winning_trades = 0
    trade_returns = []
    for i in range(0, num_trades-1, 2):
        if i+1 < num_trades:
            buy_price = transactions_df.iloc[i]['Price']
            sell_price = transactions_df.iloc[i+1]['Price']
            trade_return = (sell_price - buy_price) / buy_price * 100
            trade_returns.append(trade_return)
            if trade_return > 0:
                num_winning_trades += 1

    win_rate = num_winning_trades / len(trade_returns) * 100 if len(trade_returns) > 0 else 0
    avg_trade_days = total_days_held / (num_trades/2)
    strat_annualised = total_return / (total_days_held/365) if total_days_held > 0 else np.nan
    return_diff = final_value - buy_and_hold_value
    outperforms_bh = "Yes" if strat_annualised > buy_and_hold_annualised else "No"
    stoploss_vals = transactions_df['StopLoss%'].dropna()
    if not stoploss_vals.empty:
        min_idx = stoploss_vals.idxmin()
        worst_stoploss = stoploss_vals.loc[min_idx]
        worst_stoploss_date = transactions_df.loc[min_idx, 'StopLoss_Date']
    else:
        worst_stoploss = np.nan
        worst_stoploss_date = pd.NaT
    mod_stoploss = worst_stoploss if worst_stoploss < -10 else -10
    dollar_per_day = (final_value - initial_capital)/ total_days_held
    trade_freq = (num_trades - 10)/10 if num_trades < 11 else (num_winning_trades - 10)/20
    score = dollar_per_day * (risk_factor*((100 + worst_stoploss)/100)) * (trade_multiplier * ( 1 + trade_freq))
    run_date = portfolio_df['Date'].iloc[-1]
    stoploss_price = end_price * ((100 + mod_stoploss)/100)
    risk_price = end_price - stoploss_price
    au_size = (r_value * 0.88)/risk_price
    us_size = (r_value * 0.6)/risk_price
    uk_size = (r_value * 0.44)/risk_price
    nz_size = r_value/risk_price
    hk_size = (r_value * 4.54)/risk_price
    si_size = (r_value * 0.77)/risk_price

    print(f"Initial Capital: ${initial_capital:.2f}")
    print("\n=== Buy & Hold Strategy Performance ===")
    print(f"Buy & Hold Value: ${buy_and_hold_value:.2f}")
    print(f"Buy & Hold Return: {buy_and_hold_return:.2f}%")
    print(f"Total Days Held: {available_trading_days:.2f}")
    print("\n=== Gaussian Strategy Performance ===")
    print(f"Portfolio Value: ${final_value:.2f}")
    print(f"Difference to Buy & Hold: ${return_diff:.2f}")
    print(f"Total Return (Realised & Unrealised): {total_return:.2f}%")
    print(f"Number of Transactions: {num_trades:.2f}")
    print(f"Win Rate: {win_rate:.2f}%")
    print(f"Total Days Held: {total_days_held}")
    print(f"Worst Drawdown: {worst_stoploss:.2f}%")
    print(f"Worst drawdown Date: {worst_stoploss_date}")
    print(f"% Days Held over Strategy Period: {pct_days_held:.2f}%")
    print("\n=== Annualised Gaussian Strategy Performance ===")
    print(f"Buy & Hold Annualised rate: {buy_and_hold_annualised:.2f}%")
    print(f"Gaussian Annualised Rate: {strat_annualised:.2f}%")
    print(f" $ per day: ${dollar_per_day:.2f}")
    print("\n=== Conclusion ===")
    print(f"Strategy Outperforms Buy & Hold?: {outperforms_bh}")
    print(f"Score : {score:.2f}")
    print("\n\n=== Position sizing ===")
    print(f"Stoploss Price: ${stoploss_price:.2f}   with a Risk Premium of ${risk_price:.2f}")
    print(f" Australia quantity: {au_size:.2f}, USA quantity: {us_size:.2f}, London quantity: {uk_size:.2f}")
    print(f" New Zealand quantity: {nz_size:.2f}, Hong Kong quantity: {hk_size:.2f}, Singapore quantity: {si_size:.2f}")

def save_plot_to_file(plot_func, *args, filename, **kwargs):
    # Removed plt.figure() as plotting functions create their own figures
    plot_func(*args, **kwargs)
    plt.tight_layout()
    plt.savefig(filename, format='png', bbox_inches='tight')
    plt.close('all')
    return filename

def plot_bh_comparison(portfolio_df, ticker, train_window):
    plt.plot(portfolio_df['Date'].iloc[train_window:], portfolio_df['Portfolio_Value'].iloc[train_window:], label='Strategy', color='blue')
    start_price = portfolio_df['Stock_Price'].iloc[train_window]
    bh_line = portfolio_df['Stock_Price'] * initial_capital / start_price
    plt.plot(portfolio_df['Date'].iloc[train_window:], bh_line.iloc[train_window:], label='Buy & Hold', color='red', alpha=0.7)
    plt.title(f'Strategy vs Buy & Hold: {ticker}')
    plt.legend()
    plt.grid(True)

def plot_adx_6m(data, ticker):
    """Plot ADX (+DI/-DI) for the last 6 months"""
    plt.figure(figsize=(14, 4))
    plt.plot(data['Date'], data['ADX'], label='ADX', color='blue', linewidth=1.5)
    plt.plot(data['Date'], data['PlusDI'], label='+ADX', color='green', linewidth=1.5)
    plt.plot(data['Date'], data['MinusDI'], label='-ADX', color='red', linewidth=1.5)
    plt.axhline(25, linestyle=':', linewidth=1)  # common trend-strength threshold
    # Label latest point
    latest = data.iloc[-1]
    latest_date = latest['Date']
    plt.text(latest_date, latest['MinusDI'], f"Minus DI: {latest['MinusDI']:.2f}", color='black', fontsize=10, ha='right', va='bottom')
    plt.title(f'{ticker} ADX  — Last 6 Months')
    plt.xlabel('Date')
    plt.ylabel('Value')
    plt.legend(loc='upper left')
    plt.grid(True)

def calculate_adx(df, period: int = 14):
    """
    Wilder's ADX (+DI / -DI and ADX) using High/Low/Close.
    Adds columns: 'PlusDI', 'MinusDI', 'ADX' to df (same length, NaNs at head).
    """
    high = df['High']
    low  = df['Low']
    close = df['Close']

    up_move   = high.diff()
    down_move = (-low.diff())

    plus_dm = np.where((up_move > down_move) & (up_move > 0), up_move, 0.0)
    minus_dm = np.where((down_move > up_move) & (down_move > 0), down_move, 0.0)

    tr1 = high - low
    tr2 = (high - close.shift()).abs()
    tr3 = (low - close.shift()).abs()
    tr  = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)

    # Wilder's smoothing via EMA with alpha=1/period
    atr      = tr.ewm(alpha=1/period, adjust=False, min_periods=period).mean()
    plus_dmS = pd.Series(plus_dm, index=df.index).ewm(alpha=1/period, adjust=False, min_periods=period).mean()
    minus_dmS= pd.Series(minus_dm, index=df.index).ewm(alpha=1/period, adjust=False, min_periods=period).mean()

    plus_di  = 100 * (plus_dmS / atr)
    minus_di = 100 * (minus_dmS / atr)

    dx = 100 * (plus_di.subtract(minus_di).abs() / (plus_di + minus_di))
    adx = dx.ewm(alpha=1/period, adjust=False, min_periods=period).mean()

    df['PlusDI']  = plus_di
    df['MinusDI'] = minus_di
    df['ADX']     = adx
    return df

def collect_performance_text(portfolio_df, transactions_df, initial_capital, train_window, years):
    import io
    import sys
    old_stdout = sys.stdout
    sys.stdout = mystdout = io.StringIO()
    calculate_performance_metrics(portfolio_df, transactions_df, initial_capital, train_window, years)
    sys.stdout = old_stdout
    return mystdout.getvalue()

def process_ticker_to_excel(ticker, writer, start_date, end_date, n_components, degree, std_multiplier, train_window, Card_ID):
    try:
        data = get_clean_financial_data(ticker, start_date, end_date)
        X, y, data, scaler = prepare_data(data)
        y_pred_scaled = train_models_rolling(X, y, n_components, degree, train_window)
        y_pred = scaler.inverse_transform(y_pred_scaled.reshape(-1, 1)).flatten()
        data['Predicted'] = y_pred
        data = generate_signals_rolling(data, y_pred, train_window, std_multiplier)

        data = calculate_adx(data, period=14)
        portfolio_df, transactions_df = backtest_strategy(data, initial_capital, train_window)


        # === Format and Display Transactions ===
        formatted_log = transactions_df.copy()
        numeric_cols = formatted_log.select_dtypes(include=['float64', 'float32']).columns
        formatted_log[numeric_cols] = formatted_log[numeric_cols].round(2)
        formatted_log = formatted_log.fillna("")
        print("\n=== Transaction Log (Completed Trades) ===")
        display(formatted_log[formatted_log['Type'].isin(['BUY', 'SELL'])])

        # === Display Open Trade, if any  ====
        open_trade_df = transactions_df[transactions_df['Type'] == 'SELL (Open)']

        if not open_trade_df.empty:
            print("\n=== Open Trade ===")
            display(open_trade_df)

        #===Results ===
        calculate_performance_metrics(portfolio_df, transactions_df, initial_capital, train_window, years)


        six_months_ago = data['Date'].max() - pd.DateOffset(months=6)
        recent_data = data[data['Date'] >= six_months_ago].copy()
        p3_file = save_plot_to_file(plot_recent_trading_signals_with_labels, recent_data.copy(), ticker, filename=os.path.join(PLOTS_DIR, f"{ticker}_6_months.png"))
        p4_file = save_plot_to_file(
            plot_adx_6m, recent_data.copy(), ticker,
            filename=os.path.join(PLOTS_DIR, f"{ticker}_6_months_ADX.png")
        )
        p1_file = save_plot_to_file(plot_trading_signals, data.copy(), ticker, filename=os.path.join(PLOTS_DIR, f"{ticker}_signal_chart.png"))

        return p1_file, p3_file, p4_file

    except Exception as e:
        print(f"Error processing {ticker}: {e}")
        return None, None, None

def main():
    tickers_df = pd.read_csv(TICKER_FILE)
    start_date = pd.Timestamp.today() - pd.DateOffset(years=years)
    end_date = pd.Timestamp.today()

    # Define New Zealand timezone
    nz_timezone = pytz.timezone('Pacific/Auckland')

    with pd.ExcelWriter(EXCEL_OUTPUT, engine='xlsxwriter') as writer:
        for idx, row in tickers_df.iterrows():
            ticker = row['Ticker']
            try:
                n_components = int(row['n_components'])
                degree = int(row['poly_degree'])
                std_multiplier = float(row['std_multiplier'])
                train_window = int(row['train_window'])
                card_id = row['Card_ID'] # Changed to lowercase card_id for consistency
                score = row['Score'] # Get Score for comment

                print(f"\u2007\U0001f50d Processing {ticker} with n_components={n_components}, degree={degree}, std_multiplier={std_multiplier}, train_window={train_window}")
                p1_file, p3_file, p4_file = process_ticker_to_excel(ticker, writer, start_date, end_date, n_components, degree, std_multiplier, train_window, card_id)

                if card_id and pd.notna(card_id):
                    # 1. Set the card's due date to 2 business days in the future at 9am (NZT)
                    now_nzt = datetime.now(nz_timezone)
                    future_datetime_nzt = (pd.Timestamp(now_nzt).tz_localize(None) + pd.tseries.offsets.BDay(2)).to_pydatetime()
                    future_datetime_nzt = future_datetime_nzt.replace(hour=9, minute=0, second=0, microsecond=0, tzinfo=nz_timezone)
                    trello_due_date = future_datetime_nzt.isoformat()

                    update_due_date_endpoint = f"cards/{card_id}"
                    update_due_date_payload = {'due': trello_due_date}
                    due_date_response = trello_api_request(update_due_date_endpoint, method='PUT', data=update_due_date_payload)

                    if due_date_response:
                        print(f"Successfully set due date for card {card_id} to {trello_due_date}")
                    else:
                        print(f"Failed to set due date for card {card_id}")

                    # 2. Add a comment to the card
                    comment_text = (f"Purchase parameter settings are ({n_components}, {degree}, {std_multiplier}, "
                                    f"{train_window}) with a HPI of {score:.2f}.")

                    add_comment_endpoint = f"cards/{card_id}/actions/comments"
                    add_comment_payload = {'text': comment_text}
                    comment_response = trello_api_request(add_comment_endpoint, method='POST', data=add_comment_payload)

                    if comment_response:
                        print(f"Successfully added comment to card {card_id}")
                    else:
                        print(f"Failed to add comment to card {card_id}")

                    # Attach plots (existing logic)
                    if p3_file:
                        attach_plot_to_card(card_id, p3_file, filename=f'{ticker}_6_months.png')
                    if p4_file:
                        attach_plot_to_card(card_id, p4_file, filename=f'{ticker}_6_months_ADX.png')
                    if p1_file:
                        attach_plot_to_card(card_id, p1_file, filename=f'{ticker}_signal_chart.png', set_cover=True)

            except Exception as e:
                print(f"\u26a0\ufe0f Skipping {ticker} due to missing/invalid parameters: {e}")

if __name__ == '__main__':
    main()

 🔍 Processing 0590.HK with n_components=2, degree=3, std_multiplier=3.0, train_window=189
YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2025-08-06,BUY,20.11,497.0,9996.33,30.00,-26.33,long,0,0.00,0.00,0.0,,NaT
1,2025-09-12,SELL,26.67,497.0,13253.43,39.76,13187.34,out,37,3177.58,32.58,1515.56,0.0,2025-08-06
2,2025-10-02,BUY,24.16,545.0,13167.59,39.50,-19.76,long,0,0.00,0.00,0.0,,NaT
3,2026-02-02,SELL,31.14,545.0,16971.30,50.91,16900.63,out,123,3701.88,28.89,112.35,-6.81,2025-11-04
4,2026-03-13,BUY,26.54,636.0,16879.44,50.64,-29.45,long,0,0.00,0.00,0.0,,NaT

=== Open Trade ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
5,2026-03-13,SELL (Open),26.540001,636.0,16879.440582,0.0,-29.452253,Unrealised Gain,0,-50.638322,0.0,NaN,0.0,2026-03-13

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $28272.56
Buy & Hold Return: 182.73%
Total Days Held: 2190.00

=== Gaussian Strategy Performance ===
Portfolio Value: $16849.99
Difference to Buy & Hold: $-11422.57
Total Return (Realised & Unrealised): 68.50%
Number of Transactions: 6.00
Win Rate: 66.67%
Total Days Held: 160
Worst Drawdown: -6.81%
Worst drawdown Date: 2025-11-04 00:00:00
% Days Held over Strategy Period: 7.34%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 30.45%
Gaussian Annualised Rate: 156.27%
 $ per day: $42.81

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 23.94


=== Position sizing ===
Stoploss Price: $23.89   with a Risk Premium of $2.65
 Australia quantity: 497.36, USA quantity: 339.11, London quantity: 248.68
 New Zealand quantity: 565.18, Hong Kong quantity: 2565.94, Singapore quantity: 435.19
Successfully set due date for card 69b1e565ed8d81926f094ca7 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b1e565ed8d81926f094ca7
Successfully attached 0590.HK_6_months.png to card 69b1e565ed8d81926f094ca7
Successfully attached 0590.HK_6_months_ADX.png to card 69b1e565ed8d81926f094ca7
Successfully attached 0590.HK_signal_chart.png to card 69b1e565ed8d81926f094ca7
 🔍 Processing AQLT.AX with n_components=2, degree=3, std_multiplier=1.0, train_window=189

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2023-06-14,BUY,21.72,460.0,9991.86,30.00,-21.86,long,0,0.00,0.00,0.00,,NaT
1,2023-08-07,SELL,22.44,460.0,10321.34,30.96,10268.51,out,54,267.54,3.30,24.52,-1.68,2023-07-10
2,2023-11-03,BUY,21.64,474.0,10256.24,30.77,-18.50,long,0,0.00,0.00,0.00,,NaT
3,2024-01-05,SELL,23.71,474.0,11239.86,33.72,11187.63,out,63,916.17,9.59,69.99,0.0,2023-11-03
4,2024-01-23,BUY,24.19,462.0,11176.97,33.53,-22.86,long,0,0.00,0.00,0.00,,NaT
5,2024-03-13,SELL,25.84,462.0,11940.00,35.82,11881.32,out,50,691.40,6.83,61.94,-0.11,2024-01-24
6,2024-05-08,BUY,26.05,456.0,11877.50,35.63,-31.81,long,0,0.00,0.00,0.00,,NaT
7,2024-07-23,SELL,27.57,456.0,12573.39,37.72,12503.85,out,76,620.45,5.86,31.45,-0.71,2024-05-09
8,2024-08-16,BUY,27.77,450.0,12497.86,37.49,-31.50,long,0,0.00,0.00,0.00,,NaT
9,2024-09-25,SELL,28.59,450.0,12866.07,38.60,12795.98,out,40,291.02,2.95,30.34,-0.17,2024-09-04
10,2024-11-08,BUY,29.76,429.0,12767.71,38.30,-10.04,long,0,0.00,0.00,0.00,,NaT
11,2025-02-12,SELL,30.97,429.0,13285.03,39.86,13235.14,out,96,437.61,4.05,16.30,-1.79,2024-12-20
12,2025-03-26,BUY,29.02,456.0,13234.19,39.70,-38.76,long,0,0.00,0.00,0.00,,NaT
13,2025-06-13,SELL,31.68,456.0,14446.08,43.34,14363.99,out,79,1125.21,9.16,49.90,-10.38,2025-04-07
14,2025-07-17,BUY,32.90,436.0,14343.76,43.03,-22.80,long,0,0.00,0.00,0.00,,NaT
15,2025-12-30,SELL,33.53,436.0,14618.94,43.86,14552.28,out,166,187.47,1.92,4.27,-0.45,2025-11-21

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $15112.70
Buy & Hold Return: 51.13%
Total Days Held: 2190.00

=== Gaussian Strategy Performance ===
Portfolio Value: $14552.28
Difference to Buy & Hold: $-560.42
Total Return (Realised & Unrealised): 45.52%
Number of Transactions: 16.00
Win Rate: 100.00%
Total Days Held: 624
Worst Drawdown: -10.38%
Worst drawdown Date: 2025-04-07 00:00:00
% Days Held over Strategy Period: 58.10%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 8.52%
Gaussian Annualised Rate: 26.63%
 $ per day: $7.30

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 5.88


=== Position sizing ===
Stoploss Price: $29.56   with a Risk Premium of $3.43
 Australia quantity: 385.29, USA quantity: 262.70, London quantity: 192.65
 New Zealand quantity: 437.83, Hong Kong quantity: 1987.76, Singapore quantity: 337.13
Successfully set due date for card 69b1e550a27e340f901833cb to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b1e550a27e340f901833cb
Successfully attached AQLT.AX_6_months.png to card 69b1e550a27e340f901833cb
Successfully attached AQLT.AX_6_months_ADX.png to card 69b1e550a27e340f901833cb
Successfully attached AQLT.AX_signal_chart.png to card 69b1e550a27e340f901833cb
 🔍 Processing ANZ.AX with n_components=4, degree=2, std_multiplier=2.33, train_window=189

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2020-03-24,BUY,10.74,931.0,9995.58,30.00,-25.58,long,0,0.00,0.00,0.0,,NaT
1,2020-04-17,SELL,11.97,931.0,11146.58,33.44,11087.56,out,24,1084.12,11.52,424.65,0.0,2020-03-24
2,2022-02-04,BUY,21.27,521.0,11082.62,33.25,-28.30,long,0,0.00,0.00,0.0,,NaT
3,2022-03-23,SELL,21.89,521.0,11405.81,34.22,11343.29,out,47,254.76,2.92,25.01,-8.38,2022-03-08
4,2022-06-20,BUY,17.26,657.0,11340.10,34.02,-30.83,long,0,0.00,0.00,0.0,,NaT
5,2022-07-12,SELL,18.32,657.0,12034.61,36.10,11967.68,out,22,622.30,6.12,168.1,0.0,2022-06-20
6,2024-08-02,BUY,26.60,449.0,11944.57,35.83,-12.73,long,0,0.00,0.00,0.0,,NaT
7,2024-08-23,SELL,27.15,449.0,12190.04,36.57,12140.74,out,21,172.32,2.06,42.41,-4.91,2024-08-06
8,2024-10-04,BUY,27.46,442.0,12139.24,36.42,-34.92,long,0,0.00,0.00,0.0,,NaT
9,2024-10-22,SELL,28.96,442.0,12798.63,38.40,12725.31,out,18,582.59,5.43,192.29,0.0,2024-10-04
10,2024-12-16,BUY,27.75,458.0,12711.64,38.13,-24.46,long,0,0.00,0.00,0.0,,NaT
11,2025-10-21,SELL,36.22,458.0,16588.44,49.77,16514.22,out,309,3777.28,30.50,36.95,-9.18,2025-04-09
12,2025-11-24,BUY,34.94,472.0,16491.68,49.48,-26.94,long,0,0.00,0.00,0.0,,NaT
13,2026-02-18,SELL,39.23,472.0,18516.56,55.55,18434.07,out,86,1913.78,12.28,63.48,-2.12,2025-12-01
14,2026-03-13,BUY,37.20,495.0,18414.00,55.24,-35.17,long,0,0.00,0.00,0.0,,NaT

=== Open Trade ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
15,2026-03-13,SELL (Open),37.200001,495.0,18414.000378,0.0,-35.170617,Unrealised Gain,0,-55.242001,0.0,NaN,0.0,2026-03-13

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $27368.66
Buy & Hold Return: 173.69%
Total Days Held: 2190.00

=== Gaussian Strategy Performance ===
Portfolio Value: $18378.83
Difference to Buy & Hold: $-8989.83
Total Return (Realised & Unrealised): 83.79%
Number of Transactions: 16.00
Win Rate: 87.50%
Total Days Held: 527
Worst Drawdown: -9.18%
Worst drawdown Date: 2025-04-09 00:00:00
% Days Held over Strategy Period: 24.05%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 28.95%
Gaussian Annualised Rate: 58.03%
 $ per day: $15.90

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 12.27


=== Position sizing ===
Stoploss Price: $33.48   with a Risk Premium of $3.72
 Australia quantity: 354.84, USA quantity: 241.94, London quantity: 177.42
 New Zealand quantity: 403.23, Hong Kong quantity: 1830.65, Singapore quantity: 310.48
Successfully set due date for card 69b1e54cd9e0d525ea19a3cc to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b1e54cd9e0d525ea19a3cc
Successfully attached ANZ.AX_6_months.png to card 69b1e54cd9e0d525ea19a3cc
Successfully attached ANZ.AX_6_months_ADX.png to card 69b1e54cd9e0d525ea19a3cc
Successfully attached ANZ.AX_signal_chart.png to card 69b1e54cd9e0d525ea19a3cc
 🔍 Processing 9896.HK with n_components=4, degree=1, std_multiplier=1.33, train_window=504

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2024-11-11,BUY,37.81,264.0,9980.80,30.00,-10.80,long,0,0.00,0.00,0.0,,NaT
1,2024-12-09,SELL,46.87,264.0,12374.08,37.12,12326.16,out,28,2319.04,23.98,1547.62,-15.42,2024-11-22
2,2025-04-25,BUY,32.65,377.0,12309.51,36.93,-20.27,long,0,0.00,0.00,0.0,,NaT
3,2025-10-06,SELL,42.66,377.0,16082.82,48.25,16014.30,out,164,3676.82,30.65,81.32,0.0,2025-04-25
4,2026-03-13,BUY,32.90,486.0,15989.40,47.97,-23.07,long,0,0.00,0.00,0.0,,NaT

=== Open Trade ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
5,2026-03-13,SELL (Open),32.900002,486.0,15989.400742,0.0,-23.066719,Unrealised Gain,0,-47.968202,0.0,NaN,0.0,2026-03-13

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $8533.66
Buy & Hold Return: -14.66%
Total Days Held: 1733.75

=== Gaussian Strategy Performance ===
Portfolio Value: $15966.33
Difference to Buy & Hold: $7432.67
Total Return (Realised & Unrealised): 59.66%
Number of Transactions: 6.00
Win Rate: 66.67%
Total Days Held: 192
Worst Drawdown: -15.42%
Worst drawdown Date: 2024-11-22 00:00:00
% Days Held over Strategy Period: 38.63%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: -3.09%
Gaussian Annualised Rate: 113.42%
 $ per day: $31.07

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 15.77


=== Position sizing ===
Stoploss Price: $27.83   with a Risk Premium of $5.07
 Australia quantity: 260.28, USA quantity: 177.46, London quantity: 130.14
 New Zealand quantity: 295.77, Hong Kong quantity: 1342.79, Singapore quantity: 227.74
Successfully set due date for card 69b1e5632dfb1e5c67c9234e to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b1e5632dfb1e5c67c9234e
Successfully attached 9896.HK_6_months.png to card 69b1e5632dfb1e5c67c9234e
Successfully attached 9896.HK_6_months_ADX.png to card 69b1e5632dfb1e5c67c9234e
Successfully attached 9896.HK_signal_chart.png to card 69b1e5632dfb1e5c67c9234e
 🔍 Processing WPC with n_components=2, degree=3, std_multiplier=2.0, train_window=189

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2020-03-27,BUY,41.50,240.0,9959.44,30.00,10.56,long,0,0.00,0.00,0.00,,NaT
1,2021-11-02,SELL,59.94,240.0,14386.78,43.16,14354.18,out,585,4341.02,44.45,25.79,-15.24,2020-04-03
2,2022-02-01,BUY,59.79,240.0,14350.54,43.05,-39.41,long,0,0.00,0.00,0.00,,NaT
3,2022-03-09,SELL,61.27,240.0,14705.82,44.12,14622.29,out,36,267.04,2.48,28.14,-3.6,2022-02-10
4,2022-05-16,BUY,63.82,229.0,14614.31,43.84,-35.87,long,0,0.00,0.00,0.00,,NaT
5,2022-08-03,SELL,67.51,229.0,15460.55,46.38,15378.30,out,79,753.47,5.79,29.70,-0.98,2022-06-13
6,2022-10-06,BUY,57.87,265.0,15336.05,46.01,-3.76,long,0,0.00,0.00,0.00,,NaT
7,2022-11-28,SELL,62.70,265.0,16616.19,49.85,16562.58,out,53,1180.44,8.35,73.69,-4.6,2022-10-14
8,2023-10-02,BUY,45.93,360.0,16536.55,49.61,-23.58,long,0,0.00,0.00,0.00,,NaT
9,2023-11-13,SELL,46.80,360.0,16849.09,50.55,16774.97,out,42,211.45,1.89,17.67,-2.37,2023-10-04
10,2024-02-20,BUY,50.60,331.0,16747.83,50.24,-23.11,long,0,0.00,0.00,0.00,,NaT
11,2025-03-03,SELL,61.18,331.0,20251.38,60.75,20167.51,out,377,3382.03,20.92,20.19,-4.88,2024-04-16
12,2025-04-15,BUY,58.07,347.0,20148.61,60.45,-41.55,long,0,0.00,0.00,0.00,,NaT
13,2026-01-30,SELL,69.75,347.0,24203.25,72.61,24089.09,out,290,3909.42,20.12,25.96,-0.91,2025-05-14

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $17114.03
Buy & Hold Return: 71.14%
Total Days Held: 2190.00

=== Gaussian Strategy Performance ===
Portfolio Value: $24089.09
Difference to Buy & Hold: $6975.07
Total Return (Realised & Unrealised): 140.89%
Number of Transactions: 14.00
Win Rate: 100.00%
Total Days Held: 1462
Worst Drawdown: -15.24%
Worst drawdown Date: 2020-04-03 00:00:00
% Days Held over Strategy Period: 66.82%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 11.86%
Gaussian Annualised Rate: 35.17%
 $ per day: $9.64

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 6.94


=== Position sizing ===
Stoploss Price: $60.59   with a Risk Premium of $10.90
 Australia quantity: 121.12, USA quantity: 82.58, London quantity: 60.56
 New Zealand quantity: 137.64, Hong Kong quantity: 624.87, Singapore quantity: 105.98
Successfully set due date for card 69b3313f7e73fc445134ff5f to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b3313f7e73fc445134ff5f
Successfully attached WPC_6_months.png to card 69b3313f7e73fc445134ff5f
Successfully attached WPC_6_months_ADX.png to card 69b3313f7e73fc445134ff5f
Successfully attached WPC_signal_chart.png to card 69b3313f7e73fc445134ff5f
 🔍 Processing TDW with n_components=4, degree=2, std_multiplier=2.66, train_window=126

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2020-03-17,BUY,6.08,1643.0,9994.49,30.00,-24.49,long,0,0.00,0.00,0.00,,NaT
1,2022-01-28,SELL,15.51,1643.0,25482.93,76.45,25381.99,out,682,15335.55,154.97,65.02,-32.18,2020-05-15
2,2022-02-11,BUY,14.85,1709.0,25378.65,76.14,-72.79,long,0,0.00,0.00,0.00,,NaT
3,2022-03-17,SELL,21.18,1709.0,36196.62,108.59,36015.24,out,34,10600.79,42.63,4422.48,-5.66,2022-02-18
4,2022-03-31,BUY,21.74,1656.0,36001.44,108.00,-94.21,long,0,0.00,0.00,0.00,,NaT
5,2022-05-20,SELL,25.06,1656.0,41499.36,124.50,41280.66,out,50,5248.92,15.27,182.21,-10.63,2022-04-25
6,2022-06-03,BUY,26.99,1529.0,41267.71,123.80,-110.86,long,0,0.00,0.00,0.00,,NaT
7,2023-03-03,SELL,49.50,1529.0,75685.50,227.06,75347.59,out,273,33963.68,83.40,124.99,-33.2,2022-07-14
8,2023-03-21,BUY,43.22,1743.0,75332.46,226.00,-210.87,long,0,0.00,0.00,0.00,,NaT
9,2023-07-06,SELL,54.36,1743.0,94749.48,284.25,94254.36,out,107,18848.52,25.78,118.64,-8.38,2023-05-03
10,2023-11-10,BUY,60.35,1561.0,94206.35,282.62,-234.61,long,0,0.00,0.00,0.00,,NaT
11,2024-05-09,SELL,106.97,1561.0,166980.17,500.94,166244.62,out,181,71771.94,77.25,217.17,-6.86,2023-11-16
12,2025-04-09,BUY,36.66,4534.0,166216.44,498.65,-470.46,long,0,0.00,0.00,0.00,,NaT
13,2025-08-08,SELL,57.41,4534.0,260296.94,780.89,259045.58,out,121,92518.72,56.60,286.91,-11.97,2025-04-16

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $45204.37
Buy & Hold Return: 352.04%
Total Days Held: 2281.25

=== Gaussian Strategy Performance ===
Portfolio Value: $259045.58
Difference to Buy & Hold: $213841.21
Total Return (Realised & Unrealised): 2490.46%
Number of Transactions: 14.00
Win Rate: 100.00%
Total Days Held: 1448
Worst Drawdown: -33.20%
Worst drawdown Date: 2022-07-14 00:00:00
% Days Held over Strategy Period: 63.43%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 56.33%
Gaussian Annualised Rate: 627.77%
 $ per day: $171.99

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 97.66


=== Position sizing ===
Stoploss Price: $51.28   with a Risk Premium of $25.48
 Australia quantity: 51.80, USA quantity: 35.32, London quantity: 25.90
 New Zealand quantity: 58.86, Hong Kong quantity: 267.24, Singapore quantity: 45.33
Successfully set due date for card 69b3313fef773170fe7b93f1 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b3313fef773170fe7b93f1
Successfully attached TDW_6_months.png to card 69b3313fef773170fe7b93f1
Successfully attached TDW_6_months_ADX.png to card 69b3313fef773170fe7b93f1
Successfully attached TDW_signal_chart.png to card 69b3313fef773170fe7b93f1
 🔍 Processing STAF.L with n_components=3, degree=3, std_multiplier=2.0, train_window=504

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2024-10-10,BUY,28.35,352.0,9979.2,30.00,-9.20,long,0,0.00,0.00,0.00,,NaT
1,2025-03-17,SELL,32.95,352.0,11598.4,34.80,11554.40,out,158,1549.61,16.23,41.53,-33.69,2025-02-03
2,2025-04-25,BUY,26.30,439.0,11545.7,34.64,-25.93,long,0,0.00,0.00,0.00,,NaT
3,2025-05-30,SELL,39.40,439.0,17296.6,51.89,17218.78,out,35,5647.12,49.81,6670.75,-1.14,2025-05-06
4,2025-08-07,BUY,46.00,374.0,17204.0,51.61,-36.83,long,0,0.00,0.00,0.00,,NaT
5,2026-01-29,SELL,51.00,374.0,19074.0,57.22,18979.95,out,175,1755.56,10.87,24.01,-13.48,2025-09-22

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $6772.15
Buy & Hold Return: -32.28%
Total Days Held: 1733.75

=== Gaussian Strategy Performance ===
Portfolio Value: $18979.95
Difference to Buy & Hold: $12207.79
Total Return (Realised & Unrealised): 89.80%
Number of Transactions: 6.00
Win Rate: 100.00%
Total Days Held: 368
Worst Drawdown: -33.69%
Worst drawdown Date: 2025-02-03 00:00:00
% Days Held over Strategy Period: 21.25%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: -6.80%
Gaussian Annualised Rate: 89.07%
 $ per day: $24.40

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 9.71


=== Position sizing ===
Stoploss Price: $28.38   with a Risk Premium of $14.42
 Australia quantity: 91.55, USA quantity: 62.42, London quantity: 45.78
 New Zealand quantity: 104.04, Hong Kong quantity: 472.34, Singapore quantity: 80.11
Successfully set due date for card 69b3313819a48b9f8d6c5297 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b3313819a48b9f8d6c5297
Successfully attached STAF.L_6_months.png to card 69b3313819a48b9f8d6c5297
Successfully attached STAF.L_6_months_ADX.png to card 69b3313819a48b9f8d6c5297
Successfully attached STAF.L_signal_chart.png to card 69b3313819a48b9f8d6c5297
 🔍 Processing SSM.AX with n_components=3, degree=2, std_multiplier=2.33, train_window=504

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2024-06-14,BUY,1.18,8461.0,9999.44,30.00,-29.44,long,0,0.0,0.00,0.0,,NaT
1,2025-09-22,SELL,2.32,8461.0,19629.52,58.89,19541.19,out,465,9512.3,96.31,69.8,0.0,2024-06-14

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $23552.58
Buy & Hold Return: 135.53%
Total Days Held: 1733.75

=== Gaussian Strategy Performance ===
Portfolio Value: $19541.19
Difference to Buy & Hold: $-4011.40
Total Return (Realised & Unrealised): 95.41%
Number of Transactions: 2.00
Win Rate: 100.00%
Total Days Held: 465
Worst Drawdown: 0.00%
Worst drawdown Date: 2024-06-14 00:00:00
% Days Held over Strategy Period: 26.77%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 28.53%
Gaussian Annualised Rate: 74.89%
 $ per day: $20.52

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 4.10


=== Position sizing ===
Stoploss Price: $1.74   with a Risk Premium of $0.19
 Australia quantity: 6821.71, USA quantity: 4651.16, London quantity: 3410.85
 New Zealand quantity: 7751.94, Hong Kong quantity: 35193.80, Singapore quantity: 5968.99
Successfully set due date for card 69b3313125c2afa035427e28 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b3313125c2afa035427e28
Successfully attached SSM.AX_6_months.png to card 69b3313125c2afa035427e28
Successfully attached SSM.AX_6_months_ADX.png to card 69b3313125c2afa035427e28
Successfully attached SSM.AX_signal_chart.png to card 69b3313125c2afa035427e28
 🔍 Processing PLSR.L with n_components=3, degree=1, std_multiplier=1.0, train_window=126

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2025-09-05,BUY,22.6,442.0,9989.2,30.00,-19.20,long,0,0.00,0.00,0.00,,NaT
1,2025-10-28,SELL,40.2,442.0,17768.4,53.31,17695.89,out,53,7672.59,77.88,5178.47,-2.65,2025-09-17
2,2025-11-14,BUY,36.5,484.0,17666.0,53.00,-23.10,long,0,0.00,0.00,0.00,,NaT
3,2026-02-20,SELL,81.5,484.0,39446.0,118.34,39304.56,out,98,21543.32,123.29,1892.25,-9.59,2025-11-26

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $37307.69
Buy & Hold Return: 273.08%
Total Days Held: 2281.25

=== Gaussian Strategy Performance ===
Portfolio Value: $39304.56
Difference to Buy & Hold: $1996.87
Total Return (Realised & Unrealised): 293.05%
Number of Transactions: 4.00
Win Rate: 100.00%
Total Days Held: 151
Worst Drawdown: -9.59%
Worst drawdown Date: 2025-11-26 00:00:00
% Days Held over Strategy Period: 64.26%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 43.69%
Gaussian Annualised Rate: 708.36%
 $ per day: $194.07

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 70.18


=== Position sizing ===
Stoploss Price: $87.30   with a Risk Premium of $9.70
 Australia quantity: 136.08, USA quantity: 92.78, London quantity: 68.04
 New Zealand quantity: 154.64, Hong Kong quantity: 702.06, Singapore quantity: 119.07
Successfully set due date for card 69b331374d096ec20942b126 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b331374d096ec20942b126
Successfully attached PLSR.L_6_months.png to card 69b331374d096ec20942b126
Successfully attached PLSR.L_6_months_ADX.png to card 69b331374d096ec20942b126
Successfully attached PLSR.L_signal_chart.png to card 69b331374d096ec20942b126
 🔍 Processing P15.SI with n_components=3, degree=1, std_multiplier=1.0, train_window=189

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2020-04-06,BUY,0.13,78701.0,9999.90,30.00,-29.90,long,0,0.00,0.00,0.00,,NaT
1,2020-04-17,SELL,0.14,78701.0,10714.18,32.14,10652.14,out,11,650.00,7.14,886.82,0.0,2020-04-06
2,2021-05-20,BUY,0.20,54199.0,10652.14,31.96,-31.95,long,0,0.00,0.00,0.00,,NaT
3,2021-09-15,SELL,0.23,54199.0,12514.83,37.54,12445.33,out,118,1787.60,17.49,64.62,-1.45,2021-07-01
4,2021-11-03,BUY,0.24,52479.0,12445.18,37.34,-37.18,long,0,0.00,0.00,0.00,,NaT
5,2022-01-27,SELL,0.26,52479.0,13427.69,40.28,13350.23,out,85,901.95,7.89,38.58,-1.32,2021-11-15
6,2022-03-01,BUY,0.26,50933.0,13349.97,40.05,-39.80,long,0,0.00,0.00,0.00,,NaT
7,2022-06-21,SELL,0.28,50933.0,14151.36,42.45,14069.11,out,112,716.48,6.00,20.92,-3.57,2022-03-15
8,2022-08-03,BUY,0.28,50636.0,14068.84,42.21,-41.94,long,0,0.00,0.00,0.00,,NaT
9,2022-09-14,SELL,0.33,50636.0,16813.98,50.44,16721.60,out,42,2644.26,19.51,370.71,0.0,2022-08-03
10,2022-11-28,BUY,0.26,64091.0,16721.41,50.16,-49.97,long,0,0.00,0.00,0.00,,NaT
11,2023-03-03,SELL,0.27,64091.0,17155.73,51.47,17054.29,out,95,331.39,2.60,10.35,-1.3,2022-11-29
12,2023-05-15,BUY,0.24,72167.0,17054.07,51.16,-50.94,long,0,0.00,0.00,0.00,,NaT
13,2023-07-10,SELL,0.25,72167.0,18057.25,54.17,17952.14,out,56,894.84,5.88,45.14,0.0,2023-05-15
14,2023-09-05,BUY,0.20,90627.0,17952.01,53.86,-53.72,long,0,0.00,0.00,0.00,,NaT
15,2023-12-12,SELL,0.20,90627.0,18266.95,54.80,18158.43,out,98,205.35,1.75,6.69,-1.75,2023-09-06
16,2024-08-08,BUY,0.23,77458.0,18158.33,54.47,-54.38,long,0,0.00,0.00,0.00,,NaT
17,2024-10-11,SELL,0.27,77458.0,21049.44,63.15,20931.92,out,64,2764.82,15.92,132.24,0.0,2024-08-08
18,2024-11-20,BUY,0.27,78210.0,20931.77,62.80,-62.65,long,0,0.00,0.00,0.00,,NaT
19,2025-01-03,SELL,0.28,78210.0,21575.83,64.73,21448.45,out,44,514.60,3.08,28.58,-1.54,2024-11-29
20,2025-04-11,BUY,0.33,65114.0,21448.39,64.35,-64.29,long,0,0.00,0.00,0.00,,NaT
21,2025-05-08,SELL,0.35,65114.0,23032.12,69.10,22898.74,out,27,1445.54,7.38,161.97,0.0,2025-04-11
22,2025-11-17,BUY,0.44,51457.0,22898.36,68.70,-68.32,long,0,0.00,0.00,0.00,,NaT
23,2026-02-16,SELL,0.50,51457.0,25471.22,76.41,25326.48,out,91,2420.02,11.24,53.28,-2.25,2025-11-21

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $38273.94
Buy & Hold Return: 282.74%
Total Days Held: 2190.00

=== Gaussian Strategy Performance ===
Portfolio Value: $25326.48
Difference to Buy & Hold: $-12947.46
Total Return (Realised & Unrealised): 153.26%
Number of Transactions: 24.00
Win Rate: 100.00%
Total Days Held: 843
Worst Drawdown: -3.57%
Worst drawdown Date: 2022-03-15 00:00:00
% Days Held over Strategy Period: 38.53%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 47.12%
Gaussian Annualised Rate: 66.36%
 $ per day: $18.18

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 19.28


=== Position sizing ===
Stoploss Price: $0.45   with a Risk Premium of $0.05
 Australia quantity: 26666.67, USA quantity: 18181.82, London quantity: 13333.33
 New Zealand quantity: 30303.03, Hong Kong quantity: 137575.76, Singapore quantity: 23333.33
Successfully set due date for card 69b1e583c3709b67437fc562 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b1e583c3709b67437fc562
Successfully attached P15.SI_6_months.png to card 69b1e583c3709b67437fc562
Successfully attached P15.SI_6_months_ADX.png to card 69b1e583c3709b67437fc562
Successfully attached P15.SI_signal_chart.png to card 69b1e583c3709b67437fc562
 🔍 Processing OCFC with n_components=4, degree=1, std_multiplier=1.33, train_window=189

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2020-03-26,BUY,11.93,838.0,9995.73,30.00,-25.73,long,0,0.00,0.00,0.00,,NaT
1,2020-06-01,SELL,13.09,838.0,10970.81,32.91,10912.16,out,67,909.25,9.75,66.04,-11.72,2020-05-14
2,2021-02-03,BUY,15.16,719.0,10897.16,32.69,-17.68,long,0,0.00,0.00,0.00,,NaT
3,2021-03-22,SELL,19.33,719.0,13901.33,41.70,13841.94,out,47,2920.77,27.57,562.52,0.0,2021-02-03
4,2021-06-25,BUY,17.14,807.0,13828.36,41.49,-27.90,long,0,0.00,0.00,0.00,,NaT
5,2021-10-06,SELL,17.92,807.0,14461.88,43.39,14390.60,out,103,546.75,4.58,17.20,-10.5,2021-07-19
6,2021-11-09,BUY,18.34,784.0,14380.52,43.14,-33.06,long,0,0.00,0.00,0.00,,NaT
7,2022-01-13,SELL,19.74,784.0,15477.22,46.43,15397.73,out,65,1003.85,7.63,51.09,-7.04,2021-12-13
8,2022-04-21,BUY,16.27,946.0,15392.34,46.18,-40.78,long,0,0.00,0.00,0.00,,NaT
9,2022-08-04,SELL,17.49,946.0,16542.31,49.63,16451.90,out,105,1050.72,7.47,28.46,-5.23,2022-04-27
10,2022-09-12,BUY,16.98,969.0,16450.49,49.35,-47.94,long,0,0.00,0.00,0.00,,NaT
11,2022-11-21,SELL,19.87,969.0,19257.22,57.77,19151.51,out,70,2691.19,17.06,127.37,-6.71,2022-09-30
12,2023-01-24,BUY,19.50,981.0,19134.04,57.40,-39.94,long,0,0.00,0.00,0.00,,NaT
13,2023-02-10,SELL,21.04,981.0,20638.99,61.92,20537.13,out,17,1381.11,7.87,408.14,0.0,2023-01-24
14,2023-05-17,BUY,12.56,1634.0,20530.30,61.59,-54.76,long,0,0.00,0.00,0.00,,NaT
15,2023-06-20,SELL,14.23,1634.0,23254.29,69.76,23129.77,out,34,2584.46,13.27,280.95,-0.84,2023-05-31
16,2023-10-06,BUY,12.58,1839.0,23126.68,69.38,-66.29,long,0,0.00,0.00,0.00,,NaT
17,2024-01-03,SELL,15.20,1839.0,27958.57,83.88,27808.41,out,89,4664.14,20.89,117.74,-13.12,2023-10-25
18,2024-08-15,BUY,15.21,1828.0,27802.79,83.41,-77.79,long,0,0.00,0.00,0.00,,NaT
19,2024-09-24,SELL,16.73,1828.0,30586.47,91.76,30416.92,out,40,2600.17,10.01,138.86,0.0,2024-08-15
20,2025-01-07,BUY,16.92,1797.0,30401.87,91.21,-76.15,long,0,0.00,0.00,0.00,,NaT
21,2025-09-09,SELL,17.60,1797.0,31631.34,94.89,31460.30,out,245,1039.69,4.04,6.08,-16.66,2025-04-11
22,2026-01-16,BUY,18.13,1734.0,31445.19,94.34,-79.22,long,0,0.00,0.00,0.00,,NaT
23,2026-02-10,SELL,19.34,1734.0,33535.56,100.61,33355.73,out,25,1889.16,6.65,155.91,-2.24,2026-01-20

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $17023.06
Buy & Hold Return: 70.23%
Total Days Held: 2190.00

=== Gaussian Strategy Performance ===
Portfolio Value: $33355.73
Difference to Buy & Hold: $16332.67
Total Return (Realised & Unrealised): 233.56%
Number of Transactions: 24.00
Win Rate: 100.00%
Total Days Held: 907
Worst Drawdown: -16.66%
Worst drawdown Date: 2025-04-11 00:00:00
% Days Held over Strategy Period: 41.45%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 11.71%
Gaussian Annualised Rate: 93.99%
 $ per day: $25.75

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 23.61


=== Position sizing ===
Stoploss Price: $14.84   with a Risk Premium of $2.97
 Australia quantity: 444.88, USA quantity: 303.32, London quantity: 222.44
 New Zealand quantity: 505.54, Hong Kong quantity: 2295.15, Singapore quantity: 389.27
Successfully set due date for card 69b3313c54c12eddfebb7244 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b3313c54c12eddfebb7244
Successfully attached OCFC_6_months.png to card 69b3313c54c12eddfebb7244
Successfully attached OCFC_6_months_ADX.png to card 69b3313c54c12eddfebb7244
Successfully attached OCFC_signal_chart.png to card 69b3313c54c12eddfebb7244
 🔍 Processing NBN with n_components=4, degree=1, std_multiplier=1.33, train_window=189

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2020-03-30,BUY,12.20,819.0,9989.10,30.00,-19.10,long,0,0.00,0.00,0.00,,NaT
1,2020-05-06,SELL,14.95,819.0,12243.81,36.73,12187.97,out,37,2181.24,22.57,644.65,-18.66,2020-04-02
2,2021-04-06,BUY,26.89,453.0,12182.63,36.55,-31.21,long,0,0.00,0.00,0.00,,NaT
3,2021-08-20,SELL,33.56,453.0,15201.95,45.61,15125.13,out,136,2928.10,24.78,81.16,-2.07,2021-04-20
4,2021-09-17,BUY,33.11,456.0,15098.10,45.29,-18.27,long,0,0.00,0.00,0.00,,NaT
5,2021-10-14,SELL,35.62,456.0,16243.42,48.73,16176.42,out,27,1047.85,7.59,168.71,-3.52,2021-09-20
6,2021-11-09,BUY,34.70,466.0,16172.43,48.52,-44.53,long,0,0.00,0.00,0.00,,NaT
7,2021-12-22,SELL,35.02,466.0,16321.10,48.96,16227.61,out,43,50.74,0.92,8.08,-7.5,2021-12-01
8,2022-04-12,BUY,34.69,467.0,16202.04,48.61,-23.04,long,0,0.00,0.00,0.00,,NaT
9,2022-04-26,SELL,36.22,467.0,16914.58,50.74,16840.79,out,14,611.05,4.40,207.12,0.0,2022-04-12
10,2022-06-16,BUY,34.76,484.0,16825.33,50.48,-35.02,long,0,0.00,0.00,0.00,,NaT
11,2022-07-08,SELL,37.81,484.0,18297.85,54.89,18207.94,out,22,1362.73,8.75,302.27,-2.24,2022-06-24
12,2022-09-16,BUY,40.20,452.0,18170.09,54.51,-16.66,long,0,0.00,0.00,0.00,,NaT
13,2022-11-16,SELL,42.78,452.0,19338.15,58.01,19263.48,out,61,1052.03,6.43,45.18,-8.98,2022-09-30
14,2022-12-29,BUY,42.21,456.0,19249.89,57.75,-44.16,long,0,0.00,0.00,0.00,,NaT
15,2023-02-08,SELL,46.25,456.0,21088.33,63.26,20980.90,out,41,1711.91,9.55,125.25,-2.91,2023-01-05
16,2023-04-12,BUY,35.00,599.0,20963.02,62.89,-45.00,long,0,0.00,0.00,0.00,,NaT
17,2023-06-23,SELL,40.87,599.0,24479.63,73.44,24361.19,out,72,3369.73,16.78,119.50,-0.74,2023-04-14
18,2024-01-23,BUY,53.81,452.0,24321.87,72.97,-33.65,long,0,0.00,0.00,0.00,,NaT
19,2024-05-30,SELL,56.36,452.0,25473.56,76.42,25363.49,out,128,998.85,4.74,14.10,-8.24,2024-03-14
20,2024-08-15,BUY,66.17,383.0,25343.19,76.03,-55.72,long,0,0.00,0.00,0.00,,NaT
21,2024-10-04,SELL,75.81,383.0,29036.92,87.11,28894.08,out,50,3519.51,14.57,169.99,-0.36,2024-08-21
22,2025-01-07,BUY,92.87,311.0,28883.54,86.65,-76.11,long,0,0.00,0.00,0.00,,NaT
23,2025-09-09,SELL,110.82,311.0,34464.25,103.39,34284.74,out,245,5373.92,19.32,30.11,-13.23,2025-06-04
24,2025-10-22,BUY,94.90,361.0,34259.26,102.78,-77.30,long,0,0.00,0.00,0.00,,NaT
25,2025-12-31,SELL,103.92,361.0,37515.62,112.55,37325.78,out,70,3031.27,9.51,60.55,-13.89,2025-11-17

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $86613.58
Buy & Hold Return: 766.14%
Total Days Held: 2190.00

=== Gaussian Strategy Performance ===
Portfolio Value: $37325.78
Difference to Buy & Hold: $-49287.80
Total Return (Realised & Unrealised): 273.26%
Number of Transactions: 26.00
Win Rate: 100.00%
Total Days Held: 946
Worst Drawdown: -18.66%
Worst drawdown Date: 2020-04-02 00:00:00
% Days Held over Strategy Period: 43.24%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 127.69%
Gaussian Annualised Rate: 105.43%
 $ per day: $28.89

=== Conclusion ===
Strategy Outperforms Buy & Hold?: No
Score : 27.02


=== Position sizing ===
Stoploss Price: $88.80   with a Risk Premium of $20.37
 Australia quantity: 64.79, USA quantity: 44.17, London quantity: 32.39
 New Zealand quantity: 73.62, Hong Kong quantity: 334.24, Singapore quantity: 56.69
Successfully set due date for card 69b331399f3064e8b47c9f3e to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b331399f3064e8b47c9f3e
Successfully attached NBN_6_months.png to card 69b331399f3064e8b47c9f3e
Successfully attached NBN_6_months_ADX.png to card 69b331399f3064e8b47c9f3e
Successfully attached NBN_signal_chart.png to card 69b331399f3064e8b47c9f3e
 🔍 Processing MTUM.AX with n_components=4, degree=3, std_multiplier=2.33, train_window=252

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2025-11-21,BUY,28.17,354.0,9972.75,30.00,-2.75,long,0,0.00,0.00,0.00,,NaT
1,2025-12-30,SELL,28.74,354.0,10175.64,30.53,10142.36,out,39,141.83,2.03,20.74,-0.04,2025-12-09

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $9306.08
Buy & Hold Return: -6.94%
Total Days Held: 2098.75

=== Gaussian Strategy Performance ===
Portfolio Value: $10142.36
Difference to Buy & Hold: $836.27
Total Return (Realised & Unrealised): 1.42%
Number of Transactions: 2.00
Win Rate: 100.00%
Total Days Held: 39
Worst Drawdown: -0.04%
Worst drawdown Date: 2025-12-09 00:00:00
% Days Held over Strategy Period: 28.89%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: -1.21%
Gaussian Annualised Rate: 13.32%
 $ per day: $3.65

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 0.73


=== Position sizing ===
Stoploss Price: $25.00   with a Risk Premium of $2.78
 Australia quantity: 475.16, USA quantity: 323.97, London quantity: 237.58
 New Zealand quantity: 539.96, Hong Kong quantity: 2451.40, Singapore quantity: 415.77
Successfully set due date for card 69b1e5555f616b905519ce85 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b1e5555f616b905519ce85
Successfully attached MTUM.AX_6_months.png to card 69b1e5555f616b905519ce85
Successfully attached MTUM.AX_6_months_ADX.png to card 69b1e5555f616b905519ce85
Successfully attached MTUM.AX_signal_chart.png to card 69b1e5555f616b905519ce85
 🔍 Processing LIN with n_components=2, degree=2, std_multiplier=1.33, train_window=189

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2020-03-26,BUY,160.06,62.0,9923.73,30.00,46.27,long,0,0.00,0.00,0.00,,NaT
1,2020-04-23,SELL,166.59,62.0,10328.79,30.99,10344.08,out,28,343.09,4.08,68.46,-7.65,2020-04-01
2,2020-09-11,BUY,231.83,44.0,10200.50,30.60,112.97,long,0,0.00,0.00,0.00,,NaT
3,2020-11-16,SELL,236.73,44.0,10416.20,31.25,10497.92,out,66,153.20,2.11,12.27,-13.29,2020-10-28
4,2021-02-03,BUY,232.66,45.0,10469.60,31.41,-3.09,long,0,0.00,0.00,0.00,,NaT
5,2021-04-08,SELL,263.62,45.0,11862.75,35.59,11824.07,out,64,1321.97,13.31,103.90,-2.34,2021-02-26
6,2021-06-23,BUY,266.94,44.0,11745.54,35.24,43.29,long,0,0.00,0.00,0.00,,NaT
7,2021-08-04,SELL,286.50,44.0,12605.96,37.82,12611.43,out,42,784.78,7.33,84.85,-0.03,2021-07-19
8,2021-09-24,BUY,291.83,43.0,12548.87,37.65,24.90,long,0,0.00,0.00,0.00,,NaT
9,2021-11-17,SELL,311.79,43.0,13407.14,40.22,13391.83,out,54,777.82,6.84,56.39,-5.44,2021-09-30
10,2022-02-17,BUY,282.15,47.0,13261.25,39.78,90.79,long,0,0.00,0.00,0.00,,NaT
11,2022-04-12,SELL,297.53,47.0,13983.82,41.95,14032.65,out,54,638.66,5.45,43.13,-9.36,2022-03-07
12,2022-06-23,BUY,282.29,49.0,13832.31,41.50,158.84,long,0,0.00,0.00,0.00,,NaT
13,2022-08-19,SELL,288.87,49.0,14154.79,42.46,14271.17,out,57,237.55,2.33,15.90,-9.37,2022-07-14
14,2022-09-29,BUY,257.47,55.0,14160.86,42.48,67.82,long,0,0.00,0.00,0.00,,NaT
15,2022-12-01,SELL,323.20,55.0,17775.89,53.33,17790.38,out,63,3508.37,25.53,273.31,-0.01,2022-09-30
16,2023-01-13,BUY,320.18,55.0,17609.86,52.83,127.69,long,0,0.00,0.00,0.00,,NaT
17,2023-03-08,SELL,340.10,55.0,18705.64,56.12,18777.21,out,54,983.54,6.22,50.39,-3.77,2023-02-17
18,2023-05-26,BUY,342.64,54.0,18502.40,55.51,219.31,long,0,0.00,0.00,0.00,,NaT
19,2023-12-05,SELL,392.48,54.0,21194.00,63.58,21349.73,out,193,2564.44,14.55,29.29,-0.72,2023-05-31
20,2024-01-30,BUY,396.25,53.0,21001.31,63.00,285.41,long,0,0.00,0.00,0.00,,NaT
21,2024-03-20,SELL,454.86,53.0,24107.36,72.32,24320.45,out,50,2961.41,14.79,173.71,-1.77,2024-02-05
22,2024-05-14,BUY,421.06,57.0,24000.56,72.00,247.89,long,0,0.00,0.00,0.00,,NaT
23,2024-06-27,SELL,430.34,57.0,24529.52,73.59,24703.82,out,44,381.78,2.20,19.82,-1.37,2024-05-29
24,2024-11-05,BUY,445.99,55.0,24529.51,73.59,100.72,long,0,0.00,0.00,0.00,,NaT
25,2025-02-24,SELL,450.92,55.0,24800.78,74.40,24827.10,out,111,122.47,1.11,3.68,-8.95,2025-01-06
26,2025-04-15,BUY,444.97,55.0,24473.25,73.42,280.44,long,0,0.00,0.00,0.00,,NaT
27,2025-05-30,SELL,461.36,55.0,25374.64,76.12,25578.95,out,45,749.14,3.68,34.09,-1.58,2025-04-21
28,2025-10-21,BUY,446.93,57.0,25474.85,76.42,27.67,long,0,0.00,0.00,0.00,,NaT
29,2026-01-30,SELL,455.44,57.0,25960.09,77.88,25909.88,out,101,329.48,1.90,7.06,-13.17,2025-12-08

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $33945.21
Buy & Hold Return: 239.45%
Total Days Held: 2190.00

=== Gaussian Strategy Performance ===
Portfolio Value: $25909.88
Difference to Buy & Hold: $-8035.33
Total Return (Realised & Unrealised): 159.10%
Number of Transactions: 30.00
Win Rate: 100.00%
Total Days Held: 1026
Worst Drawdown: -13.29%
Worst drawdown Date: 2020-10-28 00:00:00
% Days Held over Strategy Period: 46.89%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 39.91%
Gaussian Annualised Rate: 56.60%
 $ per day: $15.51

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 16.81


=== Position sizing ===
Stoploss Price: $428.25   with a Risk Premium of $65.67
 Australia quantity: 20.10, USA quantity: 13.71, London quantity: 10.05
 New Zealand quantity: 22.84, Hong Kong quantity: 103.71, Singapore quantity: 17.59
Successfully set due date for card 69b3313c3c6eb5cfdbb6a148 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b3313c3c6eb5cfdbb6a148
Successfully attached LIN_6_months.png to card 69b3313c3c6eb5cfdbb6a148
Successfully attached LIN_6_months_ADX.png to card 69b3313c3c6eb5cfdbb6a148
Successfully attached LIN_signal_chart.png to card 69b3313c3c6eb5cfdbb6a148
 🔍 Processing KPG.NZ with n_components=2, degree=1, std_multiplier=1.66, train_window=252

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2022-10-31,BUY,0.73,13698.0,9999.76,30.00,-29.76,long,0,0.00,0.00,0.00,,NaT
1,2023-01-09,SELL,0.74,13698.0,10155.37,30.47,10095.14,out,70,94.67,1.56,8.38,-4.97,2022-11-09
2,2023-10-03,BUY,0.74,13648.0,10095.05,30.29,-30.20,long,0,0.00,0.00,0.00,,NaT
3,2024-08-07,SELL,0.80,13648.0,10870.56,32.61,10807.75,out,309,710.28,7.68,9.14,-10.47,2023-11-01
4,2025-03-20,BUY,0.84,12916.0,10807.73,32.42,-32.40,long,0,0.00,0.00,0.00,,NaT
5,2025-09-12,SELL,1.01,12916.0,13006.27,39.02,12934.85,out,176,2120.51,20.34,46.82,-6.78,2025-04-30

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $12816.14
Buy & Hold Return: 28.16%
Total Days Held: 2098.75

=== Gaussian Strategy Performance ===
Portfolio Value: $12934.85
Difference to Buy & Hold: $118.72
Total Return (Realised & Unrealised): 29.35%
Number of Transactions: 6.00
Win Rate: 100.00%
Total Days Held: 555
Worst Drawdown: -10.47%
Worst drawdown Date: 2023-11-01 00:00:00
% Days Held over Strategy Period: 26.49%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 4.90%
Gaussian Annualised Rate: 19.30%
 $ per day: $5.29

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 2.84


=== Position sizing ===
Stoploss Price: $0.86   with a Risk Premium of $0.10
 Australia quantity: 13207.68, USA quantity: 9005.24, London quantity: 6603.84
 New Zealand quantity: 15008.73, Hong Kong quantity: 68139.62, Singapore quantity: 11556.72
Successfully set due date for card 69b1e57bc319ca88fcf192df to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b1e57bc319ca88fcf192df
Successfully attached KPG.NZ_6_months.png to card 69b1e57bc319ca88fcf192df
Successfully attached KPG.NZ_6_months_ADX.png to card 69b1e57bc319ca88fcf192df
Successfully attached KPG.NZ_signal_chart.png to card 69b1e57bc319ca88fcf192df
 🔍 Processing J36.SI with n_components=4, degree=1, std_multiplier=2.0, train_window=189

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2020-03-24,BUY,36.10,277.0,9998.50,30.00,-28.50,long,0,0.00,0.00,0.00,,NaT
1,2020-04-13,SELL,39.08,277.0,10826.04,32.48,10765.06,out,20,762.58,8.28,326.83,-0.57,2020-03-25
2,2020-05-05,BUY,34.71,310.0,10759.76,32.28,-26.98,long,0,0.00,0.00,0.00,,NaT
3,2020-10-30,SELL,35.56,310.0,11023.82,33.07,10963.77,out,178,197.91,2.45,5.10,-13.33,2020-08-03
4,2021-02-25,BUY,42.43,258.0,10945.93,32.84,-15.01,long,0,0.00,0.00,0.00,,NaT
5,2021-03-25,SELL,53.51,258.0,13806.79,41.42,13750.36,out,28,2778.02,26.14,1963.10,-2.49,2021-03-01
6,2022-06-29,BUY,44.55,308.0,13721.43,41.16,-12.23,long,0,0.00,0.00,0.00,,NaT
7,2022-08-05,SELL,45.58,308.0,14037.19,42.11,13982.85,out,37,231.54,2.30,25.16,-1.79,2022-07-14
8,2022-11-01,BUY,40.51,345.0,13975.74,41.93,-34.82,long,0,0.00,0.00,0.00,,NaT
9,2023-06-22,SELL,45.06,345.0,15545.09,46.64,15463.64,out,233,1476.08,11.23,18.14,-2.41,2022-11-18
10,2024-12-31,BUY,39.02,396.0,15452.53,46.36,-35.25,long,0,0.00,0.00,0.00,,NaT
11,2025-03-25,SELL,41.97,396.0,16621.07,49.86,16535.96,out,84,1068.82,7.56,37.27,-5.42,2025-02-10
12,2025-10-22,BUY,62.78,263.0,16511.14,49.53,-24.71,long,0,0.00,0.00,0.00,,NaT
13,2025-11-19,SELL,63.64,263.0,16737.32,50.21,16662.40,out,28,125.76,1.37,19.41,-6.42,2025-10-31

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $20186.29
Buy & Hold Return: 101.86%
Total Days Held: 2190.00

=== Gaussian Strategy Performance ===
Portfolio Value: $16662.40
Difference to Buy & Hold: $-3523.90
Total Return (Realised & Unrealised): 66.62%
Number of Transactions: 14.00
Win Rate: 100.00%
Total Days Held: 608
Worst Drawdown: -13.33%
Worst drawdown Date: 2020-08-03 00:00:00
% Days Held over Strategy Period: 27.79%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 16.98%
Gaussian Annualised Rate: 40.00%
 $ per day: $10.96

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 8.07


=== Position sizing ===
Stoploss Price: $66.65   with a Risk Premium of $10.25
 Australia quantity: 128.74, USA quantity: 87.78, London quantity: 64.37
 New Zealand quantity: 146.29, Hong Kong quantity: 664.17, Singapore quantity: 112.65
Successfully set due date for card 69b0afd8905de2be843ef2a7 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b0afd8905de2be843ef2a7
Successfully attached J36.SI_6_months.png to card 69b0afd8905de2be843ef2a7
Successfully attached J36.SI_6_months_ADX.png to card 69b0afd8905de2be843ef2a7
Successfully attached J36.SI_signal_chart.png to card 69b0afd8905de2be843ef2a7
 🔍 Processing HLN.L with n_components=3, degree=1, std_multiplier=1.33, train_window=189

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2023-08-09,BUY,328.51,30.0,9855.38,30.00,114.62,long,0,0.00,0.00,0.00,,NaT
1,2023-10-06,SELL,337.18,30.0,10115.33,30.35,10199.61,out,58,199.26,2.64,17.80,-4.82,2023-09-06
2,2023-12-08,BUY,324.68,31.0,10065.15,30.20,104.26,long,0,0.00,0.00,0.00,,NaT
3,2024-01-17,SELL,329.18,31.0,10204.60,30.61,10278.25,out,40,78.22,1.39,13.38,-2.2,2023-12-15
4,2024-11-21,BUY,372.33,27.0,10052.97,30.16,195.12,long,0,0.00,0.00,0.00,,NaT
5,2025-02-14,SELL,384.23,27.0,10374.21,31.12,10538.21,out,85,259.00,3.20,14.46,-1.45,2025-01-15
6,2025-04-22,BUY,386.33,27.0,10430.90,31.29,76.01,long,0,0.00,0.00,0.00,,NaT
7,2025-05-14,SELL,394.38,27.0,10648.15,31.94,10692.22,out,22,153.36,2.08,40.78,-2.58,2025-04-30
8,2025-07-25,BUY,365.48,29.0,10598.85,31.80,61.57,long,0,0.00,0.00,0.00,,NaT
9,2025-11-28,SELL,370.90,29.0,10756.10,32.27,10785.40,out,126,92.71,1.48,4.36,-10.64,2025-09-25

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $11449.06
Buy & Hold Return: 14.49%
Total Days Held: 2190.00

=== Gaussian Strategy Performance ===
Portfolio Value: $10785.40
Difference to Buy & Hold: $-663.66
Total Return (Realised & Unrealised): 7.85%
Number of Transactions: 10.00
Win Rate: 100.00%
Total Days Held: 331
Worst Drawdown: -10.64%
Worst drawdown Date: 2025-09-25 00:00:00
% Days Held over Strategy Period: 34.19%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 2.42%
Gaussian Annualised Rate: 8.66%
 $ per day: $2.37

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 2.12


=== Position sizing ===
Stoploss Price: $334.93   with a Risk Premium of $39.87
 Australia quantity: 33.11, USA quantity: 22.57, London quantity: 16.55
 New Zealand quantity: 37.62, Hong Kong quantity: 170.81, Singapore quantity: 28.97
Successfully set due date for card 69b33134a933a20e1a3d7b79 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b33134a933a20e1a3d7b79
Successfully attached HLN.L_6_months.png to card 69b33134a933a20e1a3d7b79
Successfully attached HLN.L_6_months_ADX.png to card 69b33134a933a20e1a3d7b79
Successfully attached HLN.L_signal_chart.png to card 69b33134a933a20e1a3d7b79
 🔍 Processing GLIN.AX with n_components=4, degree=3, std_multiplier=1.66, train_window=126

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2024-06-04,BUY,23.99,416.0,9979.97,30.00,-9.97,long,0,0.00,0.00,0.00,,NaT
1,2024-07-18,SELL,24.35,416.0,10130.29,30.39,10089.94,out,44,89.54,1.51,13.20,-3.36,2024-06-18
2,2024-08-09,BUY,24.80,406.0,10069.22,30.21,-9.49,long,0,0.00,0.00,0.00,,NaT
3,2024-10-22,SELL,26.41,406.0,10721.95,32.17,10680.29,out,74,588.40,6.48,36.32,-0.23,2024-08-12
4,2024-11-08,BUY,25.99,410.0,10657.60,31.97,-9.28,long,0,0.00,0.00,0.00,,NaT
5,2024-11-29,SELL,27.05,410.0,11088.49,33.27,11045.94,out,21,364.36,4.04,99.15,-0.15,2024-11-14
6,2024-12-18,BUY,25.62,431.0,11041.41,33.12,-28.59,long,0,0.00,0.00,0.00,,NaT
7,2025-01-09,SELL,25.64,431.0,11051.87,33.16,10990.13,out,22,-55.85,0.09,1.58,-2.03,2024-12-19
8,2025-04-14,BUY,26.10,421.0,10988.04,32.96,-30.87,long,0,0.00,0.00,0.00,,NaT
9,2025-04-29,SELL,26.75,421.0,11260.47,33.78,11195.81,out,15,204.87,2.48,81.47,0.0,2025-04-14
10,2025-11-05,BUY,28.57,391.0,11172.20,33.52,-9.91,long,0,0.00,0.00,0.00,,NaT
11,2025-11-18,SELL,28.91,391.0,11304.37,33.91,11260.55,out,13,64.34,1.18,39.13,-0.03,2025-11-07
12,2025-12-12,BUY,28.52,394.0,11238.34,33.72,-11.50,long,0,0.00,0.00,0.00,,NaT
13,2026-02-20,SELL,31.69,394.0,12485.86,37.46,12436.90,out,70,1172.61,11.10,73.13,-0.63,2025-12-22

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $13600.61
Buy & Hold Return: 36.01%
Total Days Held: 2281.25

=== Gaussian Strategy Performance ===
Portfolio Value: $12436.90
Difference to Buy & Hold: $-1163.70
Total Return (Realised & Unrealised): 24.37%
Number of Transactions: 14.00
Win Rate: 100.00%
Total Days Held: 259
Worst Drawdown: -3.36%
Worst drawdown Date: 2024-06-18 00:00:00
% Days Held over Strategy Period: 37.65%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 5.76%
Gaussian Annualised Rate: 34.34%
 $ per day: $9.41

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 7.73


=== Position sizing ===
Stoploss Price: $28.22   with a Risk Premium of $3.14
 Australia quantity: 421.05, USA quantity: 287.08, London quantity: 210.53
 New Zealand quantity: 478.47, Hong Kong quantity: 2172.25, Singapore quantity: 368.42
Successfully set due date for card 69b1e560df72f1fb4542ab6c to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b1e560df72f1fb4542ab6c
Successfully attached GLIN.AX_6_months.png to card 69b1e560df72f1fb4542ab6c
Successfully attached GLIN.AX_6_months_ADX.png to card 69b1e560df72f1fb4542ab6c
Successfully attached GLIN.AX_signal_chart.png to card 69b1e560df72f1fb4542ab6c
 🔍 Processing FBP with n_components=4, degree=1, std_multiplier=1.66, train_window=189

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2020-03-27,BUY,4.45,2246.0,9997.22,30.00,-27.22,long,0,0.00,0.00,0.00,,NaT
1,2020-06-11,SELL,4.50,2246.0,10103.96,30.31,10046.44,out,76,46.12,1.07,5.23,-18.03,2020-04-03
2,2021-02-03,BUY,8.02,1252.0,10038.82,30.12,-22.50,long,0,0.00,0.00,0.00,,NaT
3,2021-03-17,SELL,10.10,1252.0,12641.79,37.93,12581.36,out,42,2527.12,25.93,641.55,0.0,2021-02-03
4,2021-06-25,BUY,10.66,1180.0,12576.85,37.73,-33.21,long,0,0.00,0.00,0.00,,NaT
5,2021-09-30,SELL,11.33,1180.0,13368.51,40.11,13295.20,out,97,711.46,6.29,25.82,-11.66,2021-07-19
6,2021-12-16,BUY,11.52,1154.0,13293.58,39.88,-38.26,long,0,0.00,0.00,0.00,,NaT
7,2022-01-21,SELL,12.87,1154.0,14855.17,44.57,14772.34,out,36,1472.46,11.75,208.36,-4.37,2021-12-20
8,2022-03-15,BUY,11.26,1311.0,14765.17,44.30,-37.12,long,0,0.00,0.00,0.00,,NaT
9,2022-05-03,SELL,12.14,1311.0,15910.64,47.73,15825.79,out,49,1050.01,7.76,74.47,-0.47,2022-04-07
10,2022-06-28,BUY,11.75,1347.0,15824.89,47.47,-46.57,long,0,0.00,0.00,0.00,,NaT
11,2022-08-04,SELL,13.05,1347.0,17581.89,52.75,17482.57,out,37,1651.51,11.10,182.53,-3.15,2022-06-30
12,2022-09-12,BUY,13.02,1342.0,17478.02,52.43,-47.88,long,0,0.00,0.00,0.00,,NaT
13,2022-10-21,SELL,13.80,1342.0,18515.26,55.55,18411.83,out,39,926.15,5.93,71.52,-8.19,2022-09-27
14,2022-12-22,BUY,11.32,1626.0,18403.28,55.21,-46.66,long,0,0.00,0.00,0.00,,NaT
15,2023-06-13,SELL,11.81,1626.0,19210.67,57.63,19106.37,out,173,692.12,4.39,9.48,-14.44,2023-05-12
16,2024-03-19,BUY,15.59,1225.0,19096.34,57.29,-47.26,long,0,0.00,0.00,0.00,,NaT
17,2024-07-31,SELL,20.40,1225.0,24993.06,74.98,24870.83,out,134,5746.76,30.88,108.13,-1.51,2024-04-16
18,2024-08-15,BUY,19.09,1302.0,24855.03,74.57,-58.77,long,0,0.00,0.00,0.00,,NaT
19,2024-11-11,SELL,20.78,1302.0,27050.86,81.15,26910.93,out,88,2033.52,8.83,42.07,-5.22,2024-10-25
20,2025-01-07,BUY,17.77,1514.0,26900.39,80.70,-70.16,long,0,0.00,0.00,0.00,,NaT
21,2025-02-03,SELL,19.51,1514.0,29531.95,88.60,29373.20,out,27,2454.37,9.78,253.15,-1.3,2025-01-10
22,2025-03-18,BUY,17.95,1636.0,29362.48,88.09,-77.37,long,0,0.00,0.00,0.00,,NaT
23,2025-09-02,SELL,21.80,1636.0,35669.35,107.01,35484.97,out,168,6092.85,21.48,52.61,-8.58,2025-04-07

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $49185.07
Buy & Hold Return: 391.85%
Total Days Held: 2190.00

=== Gaussian Strategy Performance ===
Portfolio Value: $35484.97
Difference to Buy & Hold: $-13700.10
Total Return (Realised & Unrealised): 254.85%
Number of Transactions: 24.00
Win Rate: 100.00%
Total Days Held: 966
Worst Drawdown: -18.03%
Worst drawdown Date: 2020-04-03 00:00:00
% Days Held over Strategy Period: 44.15%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 65.31%
Gaussian Annualised Rate: 96.29%
 $ per day: $26.38

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 23.79


=== Position sizing ===
Stoploss Price: $16.84   with a Risk Premium of $3.71
 Australia quantity: 356.26, USA quantity: 242.91, London quantity: 178.13
 New Zealand quantity: 404.85, Hong Kong quantity: 1838.00, Singapore quantity: 311.73
Successfully set due date for card 69b3313d90e7580b2971c767 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b3313d90e7580b2971c767
Successfully attached FBP_6_months.png to card 69b3313d90e7580b2971c767
Successfully attached FBP_6_months_ADX.png to card 69b3313d90e7580b2971c767
Successfully attached FBP_signal_chart.png to card 69b3313d90e7580b2971c767
 🔍 Processing DUI.AX with n_components=2, degree=2, std_multiplier=2.33, train_window=189

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2020-03-27,BUY,2.89,3455.0,9998.32,30.00,-28.32,long,0,0.00,0.00,0.00,,NaT
1,2021-06-28,SELL,4.42,3455.0,15260.38,45.78,15186.28,out,458,5170.50,52.63,40.07,0.0,2020-03-27
2,2022-02-01,BUY,4.33,3506.0,15185.36,45.56,-44.64,long,0,0.00,0.00,0.00,,NaT
3,2022-04-05,SELL,4.45,3506.0,15617.90,46.85,15526.40,out,63,338.83,2.85,17.67,-2.85,2022-03-11
4,2022-06-22,BUY,3.98,3902.0,15523.27,46.57,-43.43,long,0,0.00,0.00,0.00,,NaT
5,2022-07-14,SELL,4.23,3902.0,16521.44,49.56,16428.44,out,22,899.04,6.43,181.21,0.0,2022-06-22
6,2022-10-04,BUY,4.12,3983.0,16425.22,49.28,-46.06,long,0,0.00,0.00,0.00,,NaT
7,2023-11-22,SELL,4.50,3983.0,17930.57,53.79,17830.72,out,414,1397.77,9.16,8.04,-1.09,2022-10-10
8,2024-12-27,BUY,5.06,3526.0,17825.88,53.48,-48.64,long,0,0.00,0.00,0.00,,NaT
9,2025-05-26,SELL,5.18,3526.0,18268.83,54.81,18165.39,out,150,333.33,2.48,6.15,-5.58,2025-04-14

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $15179.25
Buy & Hold Return: 51.79%
Total Days Held: 2190.00

=== Gaussian Strategy Performance ===
Portfolio Value: $18165.39
Difference to Buy & Hold: $2986.13
Total Return (Realised & Unrealised): 81.65%
Number of Transactions: 10.00
Win Rate: 100.00%
Total Days Held: 1107
Worst Drawdown: -5.58%
Worst drawdown Date: 2025-04-14 00:00:00
% Days Held over Strategy Period: 50.52%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 8.63%
Gaussian Annualised Rate: 26.92%
 $ per day: $7.38

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 6.96


=== Position sizing ===
Stoploss Price: $4.47   with a Risk Premium of $0.50
 Australia quantity: 2655.94, USA quantity: 1810.87, London quantity: 1327.97
 New Zealand quantity: 3018.11, Hong Kong quantity: 13702.21, Singapore quantity: 2323.94
Successfully set due date for card 69b33130f33ebb7dc3beccb8 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b33130f33ebb7dc3beccb8
Successfully attached DUI.AX_6_months.png to card 69b33130f33ebb7dc3beccb8
Successfully attached DUI.AX_6_months_ADX.png to card 69b33130f33ebb7dc3beccb8
Successfully attached DUI.AX_signal_chart.png to card 69b33130f33ebb7dc3beccb8
 🔍 Processing BXE.SI with n_components=3, degree=1, std_multiplier=3.0, train_window=126

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2020-04-06,BUY,0.08,124572.0,9999.98,30.00,-29.98,long,0,0.00,0.00,0.00,,NaT
1,2020-12-14,SELL,0.13,124572.0,16592.71,49.78,16512.95,out,252,6493.17,65.93,108.22,-3.05,2020-04-30
2,2022-10-21,BUY,0.16,101247.0,16512.87,49.54,-49.46,long,0,0.00,0.00,0.00,,NaT
3,2023-06-05,SELL,0.21,101247.0,21305.82,63.92,21192.44,out,227,4665.11,29.03,50.65,0.0,2022-10-21
4,2025-01-08,BUY,0.11,184822.0,21192.33,63.58,-63.47,long,0,0.00,0.00,0.00,,NaT
5,2025-03-06,SELL,0.13,184822.0,23414.11,70.24,23280.40,out,57,2081.29,10.48,89.35,-4.03,2025-01-24

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $9119.42
Buy & Hold Return: -8.81%
Total Days Held: 2281.25

=== Gaussian Strategy Performance ===
Portfolio Value: $23280.40
Difference to Buy & Hold: $14160.97
Total Return (Realised & Unrealised): 132.80%
Number of Transactions: 6.00
Win Rate: 100.00%
Total Days Held: 536
Worst Drawdown: -4.03%
Worst drawdown Date: 2025-01-24 00:00:00
% Days Held over Strategy Period: 23.52%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: -1.41%
Gaussian Annualised Rate: 90.44%
 $ per day: $24.78

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 14.27


=== Position sizing ===
Stoploss Price: $0.09   with a Risk Premium of $0.01
 Australia quantity: 138947.37, USA quantity: 94736.84, London quantity: 69473.69
 New Zealand quantity: 157894.74, Hong Kong quantity: 716842.11, Singapore quantity: 121578.95
Successfully set due date for card 69b3314005d402fd238a5237 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b3314005d402fd238a5237
Successfully attached BXE.SI_6_months.png to card 69b3314005d402fd238a5237
Successfully attached BXE.SI_6_months_ADX.png to card 69b3314005d402fd238a5237
Successfully attached BXE.SI_signal_chart.png to card 69b3314005d402fd238a5237
 🔍 Processing AOM.L with n_components=2, degree=3, std_multiplier=1.33, train_window=126

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2022-09-22,BUY,78.0,128.0,9984.0,30.00,-14.00,long,0,0.00,0.00,0.00,,NaT
1,2023-02-07,SELL,90.0,128.0,11520.0,34.56,11471.44,out,138,1466.88,15.38,46.01,-8.97,2022-11-18
2,2023-04-13,BUY,76.0,150.0,11400.0,34.20,37.24,long,0,0.00,0.00,0.00,,NaT
3,2023-05-25,SELL,87.0,150.0,13050.0,39.15,13048.09,out,42,1571.70,14.47,223.73,-2.63,2023-04-19
4,2023-06-22,BUY,85.0,153.0,13005.0,39.02,4.08,long,0,0.00,0.00,0.00,,NaT
5,2023-07-26,SELL,107.0,153.0,16371.0,49.11,16325.96,out,34,3267.77,25.88,1083.46,-3.53,2023-06-30
6,2023-09-08,BUY,89.5,182.0,16289.0,48.87,-11.90,long,0,0.00,0.00,0.00,,NaT
7,2023-12-07,SELL,90.0,182.0,16380.0,49.14,16318.96,out,90,-7.28,0.56,2.29,-13.41,2023-11-03
8,2024-01-30,BUY,99.0,164.0,16236.0,48.71,34.25,long,0,0.00,0.00,0.00,,NaT
9,2024-02-29,SELL,106.5,164.0,17466.0,52.40,17447.85,out,30,1125.20,7.58,143.14,-2.53,2024-02-14
10,2024-03-27,BUY,100.5,173.0,17386.5,52.16,9.19,long,0,0.00,0.00,0.00,,NaT
11,2024-07-12,SELL,111.5,173.0,19289.5,57.87,19240.82,out,107,1787.26,10.95,42.52,0.0,2024-03-27
12,2024-10-08,BUY,117.5,163.0,19152.5,57.46,30.86,long,0,0.00,0.00,0.00,,NaT
13,2024-10-29,SELL,125.0,163.0,20375.0,61.12,20344.74,out,21,1100.25,6.38,193.13,0.0,2024-10-08
14,2024-11-22,BUY,116.0,175.0,20300.0,60.90,-16.16,long,0,0.00,0.00,0.00,,NaT
15,2025-05-27,SELL,121.5,175.0,21262.5,63.79,21182.55,out,186,834.92,4.74,9.52,-29.31,2025-04-09
16,2025-06-24,BUY,126.5,167.0,21125.5,63.38,-6.33,long,0,0.00,0.00,0.00,,NaT
17,2025-07-15,SELL,158.5,167.0,26469.5,79.41,26383.77,out,21,5185.18,25.30,4938.12,0.0,2025-06-24
18,2025-08-27,BUY,175.0,150.0,26250.0,78.75,55.02,long,0,0.00,0.00,0.00,,NaT
19,2025-10-24,SELL,214.0,150.0,32100.0,96.30,32058.72,out,58,5657.40,22.29,254.70,-2.86,2025-10-14
20,2025-11-21,BUY,231.0,138.0,31878.0,95.63,85.08,long,0,0.00,0.00,0.00,,NaT
21,2026-01-16,SELL,251.0,138.0,34638.0,103.91,34619.17,out,56,2552.17,8.66,71.81,-2.6,2025-12-23

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $12759.64
Buy & Hold Return: 27.60%
Total Days Held: 2281.25

=== Gaussian Strategy Performance ===
Portfolio Value: $34619.17
Difference to Buy & Hold: $21859.52
Total Return (Realised & Unrealised): 246.19%
Number of Transactions: 22.00
Win Rate: 100.00%
Total Days Held: 783
Worst Drawdown: -29.31%
Worst drawdown Date: 2025-04-09 00:00:00
% Days Held over Strategy Period: 50.84%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 4.42%
Gaussian Annualised Rate: 114.76%
 $ per day: $31.44

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 23.34


=== Position sizing ===
Stoploss Price: $151.98   with a Risk Premium of $63.02
 Australia quantity: 20.95, USA quantity: 14.28, London quantity: 10.47
 New Zealand quantity: 23.80, Hong Kong quantity: 108.07, Singapore quantity: 18.33
Successfully set due date for card 69b331355fd79dfec9543af0 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b331355fd79dfec9543af0
Successfully attached AOM.L_6_months.png to card 69b331355fd79dfec9543af0
Successfully attached AOM.L_6_months_ADX.png to card 69b331355fd79dfec9543af0
Successfully attached AOM.L_signal_chart.png to card 69b331355fd79dfec9543af0
 🔍 Processing ACT with n_components=2, degree=3, std_multiplier=1.66, train_window=126

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2022-06-27,BUY,18.78,532.0,9988.56,30.00,-18.56,long,0,0.00,0.00,0.00,,NaT
1,2022-08-19,SELL,22.66,532.0,12057.36,36.17,12002.62,out,53,1996.45,20.71,265.59,-4.52,2022-06-29
2,2022-09-23,BUY,19.40,618.0,11990.45,35.97,-23.79,long,0,0.00,0.00,0.00,,NaT
3,2022-11-02,SELL,22.47,618.0,13885.07,41.66,13819.63,out,40,1811.32,15.80,281.40,-2.62,2022-09-27
4,2023-03-16,BUY,20.35,679.0,13817.30,41.45,-39.12,long,0,0.00,0.00,0.00,,NaT
5,2023-04-20,SELL,22.09,679.0,14998.63,45.00,14914.51,out,35,1091.35,8.55,135.26,-2.86,2023-03-17
6,2023-09-11,BUY,25.76,579.0,14914.34,44.74,-44.56,long,0,0.00,0.00,0.00,,NaT
7,2024-03-18,SELL,28.05,579.0,16242.26,48.73,16148.97,out,189,1230.47,8.90,17.91,-3.9,2023-10-27
8,2024-04-23,BUY,28.70,562.0,16131.01,48.39,-30.43,long,0,0.00,0.00,0.00,,NaT
9,2024-07-31,SELL,32.76,562.0,18408.69,55.23,18323.04,out,99,2167.23,14.12,62.74,-1.41,2024-06-11
10,2024-11-08,BUY,32.67,560.0,18293.68,54.88,-25.52,long,0,0.00,0.00,0.00,,NaT
11,2024-12-06,SELL,34.13,560.0,19112.86,57.34,19030.00,out,28,704.51,4.48,77.01,0.0,2024-11-08
12,2025-04-11,BUY,34.61,549.0,18998.25,56.99,-25.25,long,0,0.00,0.00,0.00,,NaT
13,2025-05-07,SELL,35.75,549.0,19626.70,58.88,19542.57,out,26,510.68,3.31,57.91,-2.32,2025-04-21
14,2025-06-12,BUY,35.00,558.0,19530.74,58.59,-46.76,long,0,0.00,0.00,0.00,,NaT
15,2025-06-27,SELL,36.19,558.0,20195.12,60.59,20087.77,out,15,543.21,3.40,125.69,-1.49,2025-06-17
16,2025-10-16,BUY,34.66,579.0,20070.68,60.21,-43.12,long,0,0.00,0.00,0.00,,NaT
17,2025-11-17,SELL,36.51,579.0,21142.11,63.43,21035.57,out,32,944.58,5.34,80.98,-0.29,2025-10-29
18,2026-01-16,BUY,38.79,542.0,21022.37,63.07,-49.87,long,0,0.00,0.00,0.00,,NaT
19,2026-02-17,SELL,42.88,542.0,23238.94,69.72,23119.36,out,32,2077.14,10.54,213.74,-1.39,2026-01-20

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $22017.35
Buy & Hold Return: 120.17%
Total Days Held: 2281.25

=== Gaussian Strategy Performance ===
Portfolio Value: $23119.36
Difference to Buy & Hold: $1102.01
Total Return (Realised & Unrealised): 131.19%
Number of Transactions: 20.00
Win Rate: 100.00%
Total Days Held: 549
Worst Drawdown: -4.52%
Worst drawdown Date: 2022-06-29 00:00:00
% Days Held over Strategy Period: 40.19%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 19.23%
Gaussian Annualised Rate: 87.22%
 $ per day: $23.90

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 22.82


=== Position sizing ===
Stoploss Price: $36.44   with a Risk Premium of $4.05
 Australia quantity: 326.01, USA quantity: 222.28, London quantity: 163.00
 New Zealand quantity: 370.46, Hong Kong quantity: 1681.90, Singapore quantity: 285.26
Successfully set due date for card 69b3313a616d2903017d5c12 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b3313a616d2903017d5c12
Successfully attached ACT_6_months.png to card 69b3313a616d2903017d5c12
Successfully attached ACT_6_months_ADX.png to card 69b3313a616d2903017d5c12
Successfully attached ACT_signal_chart.png to card 69b3313a616d2903017d5c12
 🔍 Processing ACE.AX with n_components=3, degree=1, std_multiplier=1.33, train_window=252

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2024-07-12,BUY,0.60,16666.0,9999.60,30.00,-29.60,long,0,0.00,0.00,0.00,,NaT
1,2024-10-04,SELL,0.82,16666.0,13666.12,41.00,13595.52,out,84,3584.52,36.67,288.59,-10.0,2024-08-05
2,2025-04-10,BUY,1.00,13595.0,13595.00,40.79,-40.26,long,0,0.00,0.00,0.00,,NaT
3,2025-11-14,SELL,1.83,13595.0,24878.85,74.64,24763.95,out,218,11134.58,83.00,175.06,-14.0,2025-06-24

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $25564.52
Buy & Hold Return: 155.65%
Total Days Held: 2098.75

=== Gaussian Strategy Performance ===
Portfolio Value: $24763.95
Difference to Buy & Hold: $-800.57
Total Return (Realised & Unrealised): 147.64%
Number of Transactions: 4.00
Win Rate: 100.00%
Total Days Held: 302
Worst Drawdown: -14.00%
Worst drawdown Date: 2025-06-24 00:00:00
% Days Held over Strategy Period: 43.14%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 27.07%
Gaussian Annualised Rate: 178.44%
 $ per day: $48.89

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 16.82


=== Position sizing ===
Stoploss Price: $1.36   with a Risk Premium of $0.22
 Australia quantity: 5948.63, USA quantity: 4055.88, London quantity: 2974.31
 New Zealand quantity: 6759.80, Hong Kong quantity: 30689.50, Singapore quantity: 5205.05
Successfully set due date for card 69b3312fcb98b9c018eef16d to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b3312fcb98b9c018eef16d
Successfully attached ACE.AX_6_months.png to card 69b3312fcb98b9c018eef16d
Successfully attached ACE.AX_6_months_ADX.png to card 69b3312fcb98b9c018eef16d
Successfully attached ACE.AX_signal_chart.png to card 69b3312fcb98b9c018eef16d
 🔍 Processing 5HV.SI with n_components=4, degree=3, std_multiplier=1.66, train_window=504

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2024-08-15,BUY,0.02,434782.0,9999.99,30.00,-29.99,long,0,0.00,0.00,0.00,,NaT
1,2025-01-06,SELL,0.04,434782.0,18260.84,54.78,18176.08,out,144,8151.29,82.61,360.13,-4.35,2024-08-19
2,2025-01-16,BUY,0.04,478317.0,18176.05,54.53,-54.50,long,0,0.00,0.00,0.00,,NaT
3,2025-06-25,SELL,0.05,478317.0,25829.12,77.49,25697.13,out,160,7498.10,42.11,122.92,-2.63,2025-04-07
4,2025-11-10,BUY,0.08,313379.0,25697.08,77.09,-77.04,long,0,0.00,0.00,0.00,,NaT
5,2026-01-09,SELL,0.08,313379.0,26010.46,78.03,25855.39,out,60,157.31,1.22,7.65,-9.76,2025-11-21

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $12704.39
Buy & Hold Return: 27.04%
Total Days Held: 1733.75

=== Gaussian Strategy Performance ===
Portfolio Value: $25855.39
Difference to Buy & Hold: $13151.00
Total Return (Realised & Unrealised): 158.55%
Number of Transactions: 6.00
Win Rate: 100.00%
Total Days Held: 364
Worst Drawdown: -9.76%
Worst drawdown Date: 2025-11-21 00:00:00
% Days Held over Strategy Period: 21.04%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 5.69%
Gaussian Annualised Rate: 158.99%
 $ per day: $43.56

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 23.59


=== Position sizing ===
Stoploss Price: $0.07   with a Risk Premium of $0.01
 Australia quantity: 167088.60, USA quantity: 113924.05, London quantity: 83544.30
 New Zealand quantity: 189873.41, Hong Kong quantity: 862025.28, Singapore quantity: 146202.52
Successfully set due date for card 69b331426d6b7797e848fdff to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b331426d6b7797e848fdff
Successfully attached 5HV.SI_6_months.png to card 69b331426d6b7797e848fdff
Successfully attached 5HV.SI_6_months_ADX.png to card 69b331426d6b7797e848fdff
Successfully attached 5HV.SI_signal_chart.png to card 69b331426d6b7797e848fdff
 🔍 Processing WRB with n_components=4, degree=1, std_multiplier=2.0, train_window=126

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2020-03-30,BUY,21.35,468.0,9992.46,30.00,-22.46,long,0,0.00,0.00,0.0,,NaT
1,2021-10-12,SELL,30.49,468.0,14268.05,42.80,14202.78,out,561,4189.98,42.79,26.08,-13.89,2020-05-13
2,2021-12-06,BUY,31.85,445.0,14172.13,42.52,-11.86,long,0,0.00,0.00,0.0,,NaT
3,2022-02-15,SELL,36.46,445.0,16224.75,48.67,16164.22,out,71,1955.28,14.48,100.44,0.0,2021-12-06
4,2022-06-22,BUY,40.68,397.0,16150.39,48.45,-34.63,long,0,0.00,0.00,0.0,,NaT
5,2022-10-18,SELL,44.11,397.0,17511.79,52.54,17424.63,out,118,1256.33,8.43,28.45,-7.86,2022-08-02
6,2023-02-01,BUY,42.79,407.0,17416.15,52.25,-43.77,long,0,0.00,0.00,0.0,,NaT
7,2023-11-07,SELL,42.85,407.0,17441.48,52.32,17345.39,out,279,-79.32,0.15,0.19,-19.28,2023-05-31
8,2023-12-26,BUY,44.36,390.0,17301.71,51.91,-8.23,long,0,0.00,0.00,0.0,,NaT
9,2024-02-05,SELL,51.50,390.0,20085.78,60.26,20017.29,out,41,2663.56,16.09,277.46,-0.07,2023-12-27
10,2024-04-22,BUY,52.87,378.0,19984.46,59.95,-27.12,long,0,0.00,0.00,0.0,,NaT
11,2024-12-04,SELL,61.33,378.0,23183.98,69.55,23087.31,out,226,3060.42,16.01,27.11,-8.13,2024-04-26
12,2024-12-24,BUY,57.11,404.0,23072.18,69.22,-54.08,long,0,0.00,0.00,0.0,,NaT
13,2025-03-06,SELL,60.55,404.0,24462.93,73.39,24335.46,out,72,1243.97,6.03,34.54,-3.42,2025-01-10
14,2025-07-21,BUY,66.57,365.0,24297.26,72.89,-34.69,long,0,0.00,0.00,0.0,,NaT
15,2026-02-10,SELL,69.83,365.0,25488.49,76.47,25377.33,out,204,1038.30,4.90,8.94,-1.63,2025-12-08
16,2026-03-13,BUY,68.76,369.0,25372.44,76.12,-71.23,long,0,0.00,0.00,0.0,,NaT

=== Open Trade ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
17,2026-03-13,SELL (Open),68.760002,369.0,25372.440788,0.0,-71.225197,Unrealised Gain,0,-76.117322,0.0,NaN,0.0,2026-03-13

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $25267.91
Buy & Hold Return: 152.68%
Total Days Held: 2281.25

=== Gaussian Strategy Performance ===
Portfolio Value: $25301.22
Difference to Buy & Hold: $33.31
Total Return (Realised & Unrealised): 153.01%
Number of Transactions: 18.00
Win Rate: 88.89%
Total Days Held: 1572
Worst Drawdown: -19.28%
Worst drawdown Date: 2023-05-31 00:00:00
% Days Held over Strategy Period: 68.86%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 24.43%
Gaussian Annualised Rate: 35.53%
 $ per day: $9.73

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 7.07


=== Position sizing ===
Stoploss Price: $55.51   with a Risk Premium of $13.25
 Australia quantity: 99.59, USA quantity: 67.90, London quantity: 49.80
 New Zealand quantity: 113.17, Hong Kong quantity: 513.81, Singapore quantity: 87.14
Successfully set due date for card 69b1e5751d23dcf0e190cffc to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b1e5751d23dcf0e190cffc
Successfully attached WRB_6_months.png to card 69b1e5751d23dcf0e190cffc
Successfully attached WRB_6_months_ADX.png to card 69b1e5751d23dcf0e190cffc
Successfully attached WRB_signal_chart.png to card 69b1e5751d23dcf0e190cffc
 🔍 Processing WMK with n_components=3, degree=1, std_multiplier=2.66, train_window=126

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2020-02-05,BUY,34.18,292.0,9981.24,30.00,-11.24,long,0,0.00,0.00,0.0,,NaT
1,2020-04-13,SELL,38.72,292.0,11306.37,33.92,11261.20,out,68,1257.28,13.28,95.25,-15.37,2020-03-12
2,2022-01-18,BUY,59.05,190.0,11219.02,33.66,8.52,long,0,0.00,0.00,0.0,,NaT
3,2022-03-15,SELL,70.05,190.0,13309.76,39.93,13278.35,out,56,2010.88,18.64,204.6,-6.2,2022-01-28
4,2023-05-24,BUY,61.38,216.0,13258.57,39.78,-19.99,long,0,0.00,0.00,0.0,,NaT
5,2024-07-23,SELL,70.16,216.0,15155.48,45.47,15090.02,out,426,1805.98,14.31,12.14,-8.05,2023-05-31
6,2024-08-16,BUY,64.65,233.0,15063.11,45.19,-18.28,long,0,0.00,0.00,0.0,,NaT
7,2024-11-14,SELL,72.37,233.0,16863.16,50.59,16794.29,out,90,1698.87,11.95,58.06,-5.39,2024-10-31
8,2026-03-13,BUY,65.93,254.0,16746.22,50.24,-2.17,long,0,0.00,0.00,0.0,,NaT

=== Open Trade ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
9,2026-03-13,SELL (Open),65.93,254.0,16746.220078,0.0,-2.16825,Unrealised Gain,0,-50.23866,0.0,NaN,0.0,2026-03-13

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $18984.84
Buy & Hold Return: 89.85%
Total Days Held: 2281.25

=== Gaussian Strategy Performance ===
Portfolio Value: $16744.05
Difference to Buy & Hold: $-2240.79
Total Return (Realised & Unrealised): 67.44%
Number of Transactions: 10.00
Win Rate: 80.00%
Total Days Held: 640
Worst Drawdown: -15.37%
Worst drawdown Date: 2020-03-12 00:00:00
% Days Held over Strategy Period: 28.03%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 14.38%
Gaussian Annualised Rate: 38.46%
 $ per day: $10.54

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 8.92


=== Position sizing ===
Stoploss Price: $55.80   with a Risk Premium of $10.13
 Australia quantity: 130.29, USA quantity: 88.83, London quantity: 65.14
 New Zealand quantity: 148.05, Hong Kong quantity: 672.15, Singapore quantity: 114.00
Successfully set due date for card 69b1e574dc2df424cf2f5eab to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b1e574dc2df424cf2f5eab
Successfully attached WMK_6_months.png to card 69b1e574dc2df424cf2f5eab
Successfully attached WMK_6_months_ADX.png to card 69b1e574dc2df424cf2f5eab
Successfully attached WMK_signal_chart.png to card 69b1e574dc2df424cf2f5eab
 🔍 Processing TILE with n_components=4, degree=1, std_multiplier=1.66, train_window=252

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2022-02-02,BUY,13.13,761.0,9995.46,30.00,-25.46,long,0,0.00,0.00,0.0,,NaT
1,2022-06-14,SELL,13.18,761.0,10032.45,30.10,9976.89,out,132,-23.21,0.37,1.03,-6.85,2022-04-27
2,2022-09-30,BUY,8.90,1121.0,9975.77,30.00,-28.88,long,0,0.00,0.00,0.0,,NaT
3,2023-02-07,SELL,11.54,1121.0,12939.39,38.82,12871.70,out,130,2885.99,29.71,107.58,0.0,2022-09-30
4,2023-03-03,BUY,9.29,1385.0,12871.67,38.62,-38.59,long,0,0.00,0.00,0.0,,NaT
5,2023-08-14,SELL,10.16,1385.0,14076.23,42.23,13995.41,out,164,1120.10,9.36,22.03,-29.33,2023-05-16
6,2024-06-28,BUY,14.63,956.0,13986.93,41.96,-33.49,long,0,0.00,0.00,0.0,,NaT
7,2024-09-05,SELL,18.26,956.0,17454.81,52.36,17368.96,out,69,3363.15,24.79,222.73,-3.47,2024-07-09
8,2024-11-05,BUY,24.06,721.0,17348.48,52.05,-31.57,long,0,0.00,0.00,0.0,,NaT
9,2024-12-05,SELL,25.98,721.0,18728.76,56.19,18641.00,out,30,1267.90,7.96,153.81,0.0,2024-11-05
10,2025-01-16,BUY,23.85,781.0,18627.88,55.88,-42.76,long,0,0.00,0.00,0.0,,NaT
11,2025-08-22,SELL,27.22,781.0,21258.85,63.78,21152.32,out,218,2503.43,14.12,24.76,-25.56,2025-04-08
12,2026-03-13,BUY,27.64,765.0,21144.60,63.43,-55.71,long,0,0.00,0.00,0.0,,NaT

=== Open Trade ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
13,2026-03-13,SELL (Open),27.639999,765.0,21144.599533,0.0,-55.711465,Unrealised Gain,0,-63.433799,0.0,NaN,0.0,2026-03-13

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $33104.76
Buy & Hold Return: 231.05%
Total Days Held: 2098.75

=== Gaussian Strategy Performance ===
Portfolio Value: $21088.89
Difference to Buy & Hold: $-12015.87
Total Return (Realised & Unrealised): 110.89%
Number of Transactions: 14.00
Win Rate: 85.71%
Total Days Held: 743
Worst Drawdown: -29.33%
Worst drawdown Date: 2023-05-16 00:00:00
% Days Held over Strategy Period: 35.43%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 40.18%
Gaussian Annualised Rate: 54.47%
 $ per day: $14.92

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 8.44


=== Position sizing ===
Stoploss Price: $19.53   with a Risk Premium of $8.11
 Australia quantity: 162.80, USA quantity: 111.00, London quantity: 81.40
 New Zealand quantity: 185.00, Hong Kong quantity: 839.90, Singapore quantity: 142.45
Successfully set due date for card 69b1e571541c269ddc66edc7 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b1e571541c269ddc66edc7
Successfully attached TILE_6_months.png to card 69b1e571541c269ddc66edc7
Successfully attached TILE_6_months_ADX.png to card 69b1e571541c269ddc66edc7
Successfully attached TILE_signal_chart.png to card 69b1e571541c269ddc66edc7
 🔍 Processing SRC.L with n_components=2, degree=2, std_multiplier=3.0, train_window=189

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2020-03-26,BUY,28.8,347.0,9993.6,30.00,-23.60,long,0,0.00,0.00,0.00,,NaT
1,2022-01-17,SELL,98.0,347.0,34006.0,102.02,33880.38,out,662,23808.36,240.28,96.44,-18.4,2020-04-01
2,2024-12-19,BUY,71.4,474.0,33843.6,101.53,-64.75,long,0,0.00,0.00,0.00,,NaT
3,2025-02-18,SELL,81.0,474.0,38394.0,115.18,38214.07,out,61,4320.04,13.45,112.73,-1.4,2025-02-05

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $30471.47
Buy & Hold Return: 204.71%
Total Days Held: 2190.00

=== Gaussian Strategy Performance ===
Portfolio Value: $38214.07
Difference to Buy & Hold: $7742.60
Total Return (Realised & Unrealised): 282.14%
Number of Transactions: 4.00
Win Rate: 100.00%
Total Days Held: 723
Worst Drawdown: -18.40%
Worst drawdown Date: 2020-04-01 00:00:00
% Days Held over Strategy Period: 33.00%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 34.12%
Gaussian Annualised Rate: 142.44%
 $ per day: $39.02

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 12.74


=== Position sizing ===
Stoploss Price: $100.20   with a Risk Premium of $22.60
 Australia quantity: 58.41, USA quantity: 39.83, London quantity: 29.21
 New Zealand quantity: 66.38, Hong Kong quantity: 301.35, Singapore quantity: 51.11
Successfully set due date for card 69b1e567ad00354942b00f0c to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b1e567ad00354942b00f0c
Successfully attached SRC.L_6_months.png to card 69b1e567ad00354942b00f0c
Successfully attached SRC.L_6_months_ADX.png to card 69b1e567ad00354942b00f0c
Successfully attached SRC.L_signal_chart.png to card 69b1e567ad00354942b00f0c
 🔍 Processing 5WJ.SI with n_components=3, degree=3, std_multiplier=3.0, train_window=189

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2020-09-29,BUY,0.05,183187.0,9999.98,30.00,-29.98,long,0,0.00,0.00,0.0,,NaT
1,2021-03-10,SELL,0.08,183187.0,13905.29,41.72,13833.60,out,162,3821.88,39.05,110.18,-4.14,2020-10-20
2,2023-03-21,BUY,0.09,155905.0,13833.59,41.50,-41.49,long,0,0.00,0.00,0.0,,NaT
3,2023-04-11,SELL,0.09,155905.0,14525.27,43.58,14440.20,out,21,604.53,5.00,133.5,0.0,2023-03-21
4,2023-10-27,BUY,0.10,151387.0,14440.16,43.32,-43.28,long,0,0.00,0.00,0.0,,NaT
5,2023-11-28,SELL,0.10,151387.0,15848.95,47.55,15758.13,out,32,1313.70,9.76,189.16,0.0,2023-10-27
6,2024-10-09,BUY,0.16,97206.0,15757.99,47.27,-47.13,long,0,0.00,0.00,0.0,,NaT
7,2025-03-06,SELL,0.20,97206.0,19285.89,57.86,19180.91,out,148,3412.19,22.39,64.58,-10.45,2024-11-12
8,2025-04-10,BUY,0.18,104309.0,19180.87,57.54,-57.50,long,0,0.00,0.00,0.0,,NaT
9,2025-07-03,SELL,0.28,104309.0,28945.75,86.84,28801.41,out,84,9591.21,50.91,497.81,0.0,2025-04-10
10,2025-08-11,BUY,0.31,92164.0,28801.25,86.40,-86.25,long,0,0.00,0.00,0.0,,NaT
11,2025-08-27,SELL,0.40,92164.0,36404.78,109.21,36209.32,out,16,7385.10,26.40,20846.21,0.0,2025-08-11
12,2025-10-02,BUY,0.46,79580.0,36208.90,108.63,-108.21,long,0,0.00,0.00,0.0,,NaT
13,2026-02-03,SELL,0.75,79580.0,59287.10,177.86,59001.03,out,124,22722.48,63.74,326.92,-14.29,2025-11-27
14,2026-03-13,BUY,0.80,74215.0,59000.93,177.00,-176.90,long,0,0.00,0.00,0.0,,NaT

=== Open Trade ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
15,2026-03-13,SELL (Open),0.795,74215.0,59000.926239,0.0,-176.897263,Unrealised Gain,0,-177.002779,0.0,NaN,0.0,2026-03-13

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $188193.21
Buy & Hold Return: 1781.93%
Total Days Held: 2190.00

=== Gaussian Strategy Performance ===
Portfolio Value: $58824.03
Difference to Buy & Hold: $-129369.18
Total Return (Realised & Unrealised): 488.24%
Number of Transactions: 16.00
Win Rate: 87.50%
Total Days Held: 587
Worst Drawdown: -14.29%
Worst drawdown Date: 2025-11-27 00:00:00
% Days Held over Strategy Period: 26.83%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 296.99%
Gaussian Annualised Rate: 303.59%
 $ per day: $83.18

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 60.60


=== Position sizing ===
Stoploss Price: $0.68   with a Risk Premium of $0.11
 Australia quantity: 11622.64, USA quantity: 7924.53, London quantity: 5811.32
 New Zealand quantity: 13207.54, Hong Kong quantity: 59962.24, Singapore quantity: 10169.81
Successfully set due date for card 69b1e585e89880b80c02d873 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b1e585e89880b80c02d873
Successfully attached 5WJ.SI_6_months.png to card 69b1e585e89880b80c02d873
Successfully attached 5WJ.SI_6_months_ADX.png to card 69b1e585e89880b80c02d873
Successfully attached 5WJ.SI_signal_chart.png to card 69b1e585e89880b80c02d873
 🔍 Processing 3323.HK with n_components=3, degree=2, std_multiplier=2.33, train_window=189

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2020-09-07,BUY,7.76,1288.0,9997.52,30.00,-27.52,long,0,0.00,0.00,0.00,,NaT
1,2021-09-09,SELL,9.37,1288.0,12064.02,36.19,12000.30,out,367,1994.11,20.67,20.55,-20.16,2020-12-28
2,2021-10-11,BUY,7.60,1578.0,11994.23,35.98,-29.91,long,0,0.00,0.00,0.00,,NaT
3,2022-04-11,SELL,7.78,1578.0,12277.56,36.83,12210.82,out,182,209.66,2.36,4.79,-25.79,2022-03-15
4,2024-06-20,BUY,2.78,4388.0,12210.72,36.63,-36.54,long,0,0.00,0.00,0.00,,NaT
5,2024-10-10,SELL,3.02,4388.0,13259.75,39.78,13183.43,out,112,969.47,8.59,30.81,-29.21,2024-09-11
6,2025-09-09,BUY,5.31,2482.0,13179.42,39.54,-35.52,long,0,0.00,0.00,0.00,,NaT
7,2026-02-03,SELL,5.48,2482.0,13601.36,40.80,13525.03,out,147,340.33,3.20,8.14,-11.3,2025-12-16

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $11337.34
Buy & Hold Return: 13.37%
Total Days Held: 2190.00

=== Gaussian Strategy Performance ===
Portfolio Value: $13525.03
Difference to Buy & Hold: $2187.69
Total Return (Realised & Unrealised): 35.25%
Number of Transactions: 8.00
Win Rate: 100.00%
Total Days Held: 808
Worst Drawdown: -29.21%
Worst drawdown Date: 2024-09-11 00:00:00
% Days Held over Strategy Period: 37.05%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: 2.23%
Gaussian Annualised Rate: 15.92%
 $ per day: $4.36

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 2.47


=== Position sizing ===
Stoploss Price: $4.08   with a Risk Premium of $1.69
 Australia quantity: 783.20, USA quantity: 534.00, London quantity: 391.60
 New Zealand quantity: 890.00, Hong Kong quantity: 4040.59, Singapore quantity: 685.30
Successfully set due date for card 69b1e564bf95ab714d71f3e7 to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b1e564bf95ab714d71f3e7
Successfully attached 3323.HK_6_months.png to card 69b1e564bf95ab714d71f3e7
Successfully attached 3323.HK_6_months_ADX.png to card 69b1e564bf95ab714d71f3e7
Successfully attached 3323.HK_signal_chart.png to card 69b1e564bf95ab714d71f3e7
 🔍 Processing 1083.HK with n_components=2, degree=2, std_multiplier=2.33, train_window=126

[*********************100%***********************]  1 of 1 completed

=== Transaction Log (Completed Trades) ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
0,2021-07-30,BUY,4.18,2393.0,9999.91,30.00,-29.91,long,0,0.00,0.00,0.0,,NaT
1,2021-08-26,SELL,4.51,2393.0,10782.68,32.35,10720.42,out,27,718.08,7.83,176.99,-7.44,2021-08-02
2,2021-09-30,BUY,3.97,2697.0,10718.88,32.16,-30.62,long,0,0.00,0.00,0.0,,NaT
3,2021-11-01,SELL,4.50,2697.0,12130.43,36.39,12063.42,out,32,1338.76,13.17,310.03,-12.14,2021-10-15
4,2023-03-24,BUY,2.89,4172.0,12061.47,36.18,-34.24,long,0,0.00,0.00,0.0,,NaT
5,2023-07-28,SELL,3.35,4172.0,13957.21,41.87,13881.10,out,126,1812.00,15.72,52.63,-2.65,2023-03-27
6,2023-08-25,BUY,2.72,5111.0,13878.43,41.64,-38.97,long,0,0.00,0.00,0.0,,NaT
7,2024-10-10,SELL,3.10,5111.0,15823.77,47.47,15737.33,out,412,1850.39,14.02,12.32,-11.44,2024-02-15
8,2025-04-14,BUY,3.28,4793.0,15735.86,47.21,-45.74,long,0,0.00,0.00,0.0,,NaT
9,2026-02-03,SELL,3.57,4793.0,17111.01,51.33,17013.94,out,295,1272.48,8.74,10.92,-2.85,2025-04-16
10,2026-03-13,BUY,3.87,4396.0,17012.52,51.04,-49.62,long,0,0.00,0.00,0.0,,NaT

=== Open Trade ===

,Date,Type,Price,Shares,Value,Commission,Cash,Position,Days_Held,Profit_Loss,Pct_Return,Annualized_Return_%,StopLoss%,StopLoss_Date
11,2026-03-13,SELL (Open),3.87,4396.0,17012.519497,0.0,-49.620925,Unrealised Gain,0,-51.037558,0.0,NaN,0.0,2026-03-13

Initial Capital: $10000.00

=== Buy & Hold Strategy Performance ===
Buy & Hold Value: $8872.59
Buy & Hold Return: -11.27%
Total Days Held: 2281.25

=== Gaussian Strategy Performance ===
Portfolio Value: $16962.90
Difference to Buy & Hold: $8090.31
Total Return (Realised & Unrealised): 69.63%
Number of Transactions: 12.00
Win Rate: 83.33%
Total Days Held: 892
Worst Drawdown: -12.14%
Worst drawdown Date: 2021-10-15 00:00:00
% Days Held over Strategy Period: 39.17%

=== Annualised Gaussian Strategy Performance ===
Buy & Hold Annualised rate: -1.80%
Gaussian Annualised Rate: 28.49%
 $ per day: $7.81

=== Conclusion ===
Strategy Outperforms Buy & Hold?: Yes
Score : 5.14


=== Position sizing ===
Stoploss Price: $3.40   with a Risk Premium of $0.47
 Australia quantity: 2809.62, USA quantity: 1915.65, London quantity: 1404.81
 New Zealand quantity: 3192.75, Hong Kong quantity: 14495.07, Singapore quantity: 2458.41
Successfully set due date for card 69b1e5666aeebfd67696542f to 2026-03-17T09:00:00+11:39
Successfully added comment to card 69b1e5666aeebfd67696542f
Successfully attached 1083.HK_6_months.png to card 69b1e5666aeebfd67696542f
Successfully attached 1083.HK_6_months_ADX.png to card 69b1e5666aeebfd67696542f
Successfully attached 1083.HK_signal_chart.png to card 69b1e5666aeebfd67696542f

In [9]:
import pandas as pd
import requests
from datetime import datetime

# Trello API credentials
TRELLO_API_KEY   = "3b339a99725dc0efa820ed87b0db4541"
TRELLO_API_TOKEN = "ATTAdc78f81723bc85deb590dd40f9608ec7ec7dda4df5f9396a606240b8e4d4ea20436E01D9"

# Input file
INPUT_CSV = r"C:\\Users\\User\\OneDrive\\Momentum\\Scripts\\Signal_Archive\\todays_purchase.csv"

# Trello API base
TRELLO_BASE_URL = "https://api.trello.com/1"

# Custom field names on your Trello board (must match exactly)
CF_MAP = {
    "PARAM n-value": "n_components",
    "PARAM regression": "poly_degree",
    "PARAM sensitivity": "std_multiplier",
    "PARAM training period": "train_window",
    "HPI": "Score",
}

def trello_params(extra=None):
    p = {"key": TRELLO_API_KEY, "token": TRELLO_API_TOKEN}
    if extra:
        p.update(extra)
    return p

def build_description(row: pd.Series) -> str:
    """
    Builds the Trello card description from a dataframe row.
    """
    # Safely get 'Transactions' value, default to 0 if not found, then convert to numeric
    transactions_val = pd.to_numeric(row.get('Transactions', 0), errors='coerce')
    # Divide by 2 if it's a valid number, otherwise default to empty string
    num_trades_str = f"{transactions_val / 2:.0f}" if pd.notna(transactions_val) else ''

    lines = [
       f"Ticker: {row.get('Ticker','')}",
        "",
        f"Key Parameters: ",
        f"n-value: {row.get('n_components','')}",
        f"Regression: {row.get('poly_degree','')}",
        f"Sensitivity: {row.get('std_multiplier','')}",
        f"Training Period: {row.get('train_window','')}",
        "",
        f"Number of trades: {row.get('Number of trades','')}",
        f"Last 12 months: {row.get('Last 12 months','')}",
        f"Score: {row.get('Score','')}",
        "",
        f"Maximum Stop Loss %: {row.get('Maximum Stop Loss %','')}",
        "",
        f"Industry: {row.get('Industry','')}",
        f"Sector: {row.get('Sector','')}",
        f"Exchange: {row.get('Exchange','')}",
        "",
        f"Updated: {row.get('Run Date','')}",
    ]
    return "\n".join(lines)

def to_number_string(x):
    """
    Trello expects numeric custom field values as strings (e.g., {"number":"4"}).
    Returns None if missing/unparseable.
    """
    if pd.isna(x):
        return None
    try:
        # allow ints, floats, numeric strings
        val = float(str(x).strip())
        # Keep integers clean if they are whole numbers
        if val.is_integer():
            return str(int(val))
        return str(val)
    except Exception:
        return None

def get_card(card_id: str, timeout=15):
    url = f"{TRELLO_BASE_URL}/cards/{card_id}"
    r = requests.get(url, params=trello_params(), timeout=timeout)
    r.raise_for_status()
    return r.json()

def get_board_custom_fields(board_id: str, timeout=15):
    """
    Returns list of board custom fields.
    """
    url = f"{TRELLO_BASE_URL}/boards/{board_id}/customFields"
    r = requests.get(url, params=trello_params(), timeout=timeout)
    r.raise_for_status()
    return r.json()

def update_card_description(card_id: str, desc: str, timeout=15):
    url = f"{TRELLO_BASE_URL}/cards/{card_id}"
    r = requests.put(url, params=trello_params({"desc": desc}), timeout=timeout)
    r.raise_for_status()
    return r.json()

def update_card_custom_field_number(card_id: str, custom_field_id: str, number_as_string: str, timeout=15):
    """
    PUT /cards/{idCard}/customField/{idCustomField}/item
    Body: {"value":{"number":"<string>"}}
    """
    url = f"{TRELLO_BASE_URL}/cards/{card_id}/customField/{custom_field_id}/item"
    payload = {"value": {"number": number_as_string}}
    r = requests.put(url, params=trello_params(), json=payload, timeout=timeout)
    r.raise_for_status()
    return r.json()

df = pd.read_csv(INPUT_CSV)

# Required columns for this automation
required_cols = [
    "Card_ID", "Ticker",
    "n_components", "poly_degree", "std_multiplier", "train_window",
    "Number of trades", "Score", "Last 12 months",
    "Maximum Stop Loss %", "Run Date" , "Sector", "Industry", "Exchange"
]
missing = [c for c in required_cols if c not in df.columns]
if missing:
    raise ValueError(f"Missing required columns in {INPUT_CSV}: {missing}")

# Normalize key columns
df["Card_ID"] = df["Card_ID"].astype(str).str.strip()
df["Ticker"] = df["Ticker"].astype(str).str.strip()

ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
success_rows = []
error_rows = []

# Cache board custom-field ID lookups (board_id -> name->field_obj)
board_cf_cache = {}

for i, row in df.iterrows():
    card_id = row["Card_ID"]

    if not card_id or card_id.lower() == "nan":
        error_rows.append({"Row": i, "Card_ID": card_id, "Ticker": row.get("Ticker",""), "Step": "input", "Error": "Missing Card_ID", "Datestamp": ts})
        continue

    try:
        # 1) Get card (to discover board)
        card = get_card(card_id)
        board_id = card.get("idBoard")
        if not board_id:
            raise RuntimeError("Could not determine idBoard from card.")

        # 2) Load board custom fields (cached)
        if board_id not in board_cf_cache:
            cfs = get_board_custom_fields(board_id)
            # map by exact name
            board_cf_cache[board_id] = {cf.get("name"): cf for cf in cfs}

        cf_by_name = board_cf_cache[board_id]

        # 3) Update description
        desc = build_description(row)
        update_card_description(card_id, desc)

        # 4) Update custom fields
        for cf_name, source_col in CF_MAP.items():
            cf_obj = cf_by_name.get(cf_name)
            if not cf_obj:
                raise RuntimeError(f"Custom field '{cf_name}' not found on board {board_id}. Check spelling/case.")

            cf_id = cf_obj.get("id")
            cf_type = cf_obj.get("type")

            if cf_type != "number":
                raise RuntimeError(f"Custom field '{cf_name}' is type '{cf_type}', expected 'number'.")

            num_str = to_number_string(row.get(source_col))
            if num_str is None:
                # Decide policy: skip or fail.
                # Here: skip update for that field but record it.
                error_rows.append({
                    "Row": i, "Card_ID": card_id, "Ticker": row.get("Ticker",""),
                    "Step": f"custom_field:{cf_name}", "Error": f"Value in column '{source_col}' is blank/non-numeric; skipped.", "Datestamp": ts
                })
                continue

            update_card_custom_field_number(card_id, cf_id, num_str)

        success_rows.append({"Row": i, "Card_ID": card_id, "Ticker": row.get("Ticker",""), "Datestamp": ts})

    except requests.HTTPError as e:
        # Include response text if available
        resp_text = ""
        try:
            resp_text = e.response.text
        except Exception:
            pass
        error_rows.append({"Row": i, "Card_ID": card_id, "Ticker": row.get("Ticker",""), "Step": "http", "Error": f"{e} {resp_text}".strip(), "Datestamp": ts})
    except Exception as e:
        error_rows.append({"Row": i, "Card_ID": card_id, "Ticker": row.get("Ticker",""), "Step": "exception", "Error": str(e), "Datestamp": ts})

# Write logs
out_success = r"C:\\Users\\User\\OneDrive\\Momentum\\Scripts\\Signal_Archive\\purchase_trello_cards_update_success.csv"
out_errors   = r"C:\\Users\\User\\OneDrive\\Momentum\\Scripts\\Signal_Archive\\purchase_trello_cards_update_errors.csv"

pd.DataFrame(success_rows).to_csv(out_success, index=False)
pd.DataFrame(error_rows).to_csv(out_errors, index=False)

print(f"Done. Success: {len(success_rows)} | Errors/Warnings: {len(error_rows)}")
print(f"Success log: {out_success}")
print(f"Error log:   {out_errors}")

Done. Success: 32 | Errors/Warnings: 0
Success log: C:\\Users\\User\\OneDrive\\Momentum\\Scripts\\Signal_Archive\\purchase_trello_cards_update_success.csv
Error log:   C:\\Users\\User\\OneDrive\\Momentum\\Scripts\\Signal_Archive\\purchase_trello_cards_update_errors.csv